# SPDX-License-Identifier: Apache-2.0
"""Generate an explicit, empty-schema PostgreSQL baseline and migration runner."""

from __future__ import annotations

from typing import Any

from .models import go_name

MIGRATION_RUNNER = """// SPDX-License-Identifier: Apache-2.0
package backend
import (
    "context"
    "database/sql"
    "embed"
    "fmt"
    "io/fs"
    _ "github.com/jackc/pgx/v5/stdlib"
    "github.com/pressly/goose/v3"
    "github.com/pressly/goose/v3/lock"
)
//go:embed migrations/*.sql
var migrationFiles embed.FS

// Migrate applies or rolls back the baseline only when explicitly called.
func Migrate(ctx context.Context, dsn string, direction string) error {
    if dsn == "" { return fmt.Errorf("DATABASE_URL is required") }
    if direction != "up" && direction != "down" {
        return fmt.Errorf("direction must be up or down")
    }
    db, err := sql.Open("pgx", dsn)
    if err != nil { return err }
    defer db.Close()
    if err := db.PingContext(ctx); err != nil { return err }
    migrations, err := fs.Sub(migrationFiles, "migrations")
    if err != nil { return err }
    locker, err := lock.NewPostgresSessionLocker()
    if err != nil { return err }
    provider, err := goose.NewProvider(goose.DialectPostgres, db, migrations,
        goose.WithSessionLocker(locker))
    if err != nil { return err }
    if direction == "up" { _, err = provider.Up(ctx) } else { _, err = provider.Down(ctx) }
    return err
}
"""

COMMAND = """// SPDX-License-Identifier: Apache-2.0
package main
import (
    "context"
    "fmt"
    "os"
    "os/signal"
    "syscall"
    "time"
    backend "migrated.backend"
)
func main() {
    if len(os.Args) != 2 || (os.Args[1] != "up" && os.Args[1] != "down") {
        fmt.Fprintln(os.Stderr, "usage: migrate up|down (down deletes migrated tables)")
        os.Exit(2)
    }
    ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
    defer cancel()
    ctx, timeout := context.WithTimeout(ctx, 2*time.Minute)
    defer timeout()
    if err := backend.Migrate(ctx, os.Getenv("DATABASE_URL"), os.Args[1]); err != nil {
        fmt.Fprintln(os.Stderr, err)
        os.Exit(1)
    }
}
"""


def render_database(captured: dict[str, Any]) -> dict[str, str]:
    models = captured["models"]
    definitions = []
    sql = [
        "-- +goose Up",
        "-- +goose StatementBegin",
        """DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
               WHERE n.nspname=current_schema() AND c.relkind IN ('r','p','v','m','S','f')
               AND c.relname NOT IN ('goose_db_version','goose_db_version_id_seq')) THEN
        RAISE EXCEPTION 'baseline requires an empty schema; existing tables are never adopted';
    END IF;
END; $$;""",
        "-- +goose StatementEnd",
    ]
    for model in models:
        lines = []
        columns = []
        for field in model["fields"]:
            kind = field["sql_type"]
            suffix = ""
            if field["auto"]:
                if captured["configuration"]["source_framework"] == "drf":
                    suffix += " GENERATED BY DEFAULT AS IDENTITY"
                else:
                    kind = "bigserial" if kind == "bigint" else "serial"
            if not field["nullable"]:
                suffix += " NOT NULL"
            if field["primary_key"]:
                suffix += " PRIMARY KEY"
            elif field["unique"]:
                suffix += " UNIQUE"
            columns.append(f'    "{field["name"]}" {kind}{suffix}')
            go_type = ("*" if field["nullable"] else "") + field["go_type"]
            lines.append(
                f"    {go_name(field['name'])} {go_type} "
                f'`json:"{field["name"]}" db:"{field["name"]}"`'
            )
        definitions.append(f"type {model['name']} struct {{\n" + "\n".join(lines) + "\n}")
        sql.append(f'CREATE TABLE "{model["table"]}" (\n' + ",\n".join(columns) + "\n);")
    sql.append("-- +goose Down")
    for model in reversed(models):
        sql.append(f'DROP TABLE "{model["table"]}";')
    return {
        "models.go": "// SPDX-License-Identifier: Apache-2.0\npackage backend\n\n"
        + "\n\n".join(definitions)
        + "\n",
        "migrations/00001_initial.sql": "\n\n".join(sql) + "\n",
        "database.go": MIGRATION_RUNNER,
        "cmd/migrate/main.go": COMMAND,
        ".env.example": "# Supply the PostgreSQL URL at execution time.\nDATABASE_URL=\n",
    }
