# SPDX-License-Identifier: Apache-2.0
# ruff: noqa: E501
"""Native Go handlers for statically captured conventional DRF contracts."""

from __future__ import annotations

from importlib.resources import files
from typing import Any

from .database import render_database
from .values import GO_NATIVE_VALUES, GO_VALUES


def render_project(captured: dict[str, Any]) -> dict[str, str]:
    from .capture import canonical
    from .render import DRF_HELPERS, MODULES, QUERY_SOURCE, _runtime

    target = captured["configuration"]["target_framework"]
    lock = files("sanka_extension_python_to_golang").joinpath("locks", target + "-postgresql")
    result = {
        "contract.json": canonical(captured) + "\n",
        "go.mod": lock.joinpath("go.mod").read_text(),
        "go.sum": lock.joinpath("go.sum").read_text(),
        **render_database(captured),
        "values.go": GO_VALUES,
        "native_values.go": GO_NATIVE_VALUES,
        "query.go": QUERY_SOURCE.replace("QUERY_FIRST", "false"),
        **_runtime(target, True, True),
    }
    sqlite = captured["drf_project"]["database"]["engine"] == "sqlite"
    if not sqlite:
        from .drf_transfer import TRANSFER_SCRIPT

        result["tools/transfer_existing.py"] = TRANSFER_SCRIPT
    adopting = captured["configuration"]["schema_mode"] == "adopt-existing"
    authenticated = captured["drf_project"].get("authentication") == "jwt-hs256-roles"
    if authenticated:
        jwt_lock = files("sanka_extension_python_to_golang").joinpath("locks", "jwt")
        result["go.mod"] += "\n" + jwt_lock.joinpath("go.mod").read_text()
        result["go.sum"] = (
            "\n".join(
                sorted(
                    set(result["go.sum"].splitlines())
                    | set(jwt_lock.joinpath("go.sum").read_text().splitlines())
                )
            )
            + "\n"
        )
        result[".env.example"] += "AUTH_JWT_SECRET=\nAUTH_JWT_ISSUER=\nAUTH_JWT_AUDIENCE=\n"
    migration = result["migrations/00001_initial.sql"]
    counters = ""
    if sqlite:
        migration = migration.replace(" GENERATED BY DEFAULT AS IDENTITY", "")
        counters = "CREATE TABLE migration_identity (table_name text PRIMARY KEY, value bigint NOT NULL);\n"
    for model in captured["models"]:
        if sqlite:
            counters += f"INSERT INTO migration_identity VALUES ('{model['table']}', 0);\n"
        for field in model["fields"]:
            if field.get("kind") == "PositiveIntegerField" and not adopting:
                counters += f'ALTER TABLE "{model["table"]}" ADD CHECK ("{field["name"]}" >= 0);\n'
    result["migrations/00001_initial.sql"] = migration.replace(
        "-- +goose Down",
        counters + "\n-- +goose Down" + ("\nDROP TABLE migration_identity;" if sqlite else ""),
    )
    if target == "fiber":
        adapter = """func NewApp(pool *pgxpool.Pool) *fiber.App {
    if pool == nil { panic("NewApp requires a database pool") }
    app := fiber.New(fiber.Config{BodyLimit: 1048576, DisableHeadAutoRegister: true, ReadTimeout: 15*time.Second, WriteTimeout: 30*time.Second, IdleTimeout: 60*time.Second})
    app.Use(func(c fiber.Ctx) error {
        status, body := drfRequest(c.Context(), pool, c.Method(), c.Path(), c.Body(), c.Get("Accept"), c.Get("Content-Type"), c.Get("Authorization"), c.Get("Cookie"), c.BaseURL()+c.OriginalURL())
        if status == 401 { c.Set("WWW-Authenticate", "Bearer") }
        if status == 204 { return c.SendStatus(status) }
        return c.Status(status).JSON(body)
    })
    return app
}"""
    else:
        setup = {
            "chi": 'app := chi.NewRouter(); app.Handle("/*", handler)',
            "mux": 'app := mux.NewRouter(); app.PathPrefix("/").Handler(handler)',
            "gin": "app := gin.New(); app.RedirectTrailingSlash = false; app.NoRoute(gin.WrapH(handler))",
        }[target]
        adapter = f"""func NewApp(pool *pgxpool.Pool) http.Handler {{
    if pool == nil {{ panic("NewApp requires a database pool") }}
    handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {{
        raw, err := io.ReadAll(http.MaxBytesReader(w, r.Body, 1048576))
        if err != nil {{ w.WriteHeader(413); return }}
        scheme := "http"; if r.TLS != nil {{ scheme = "https" }}
        status, body := drfRequest(r.Context(), pool, r.Method, r.URL.Path, raw, r.Header.Get("Accept"), r.Header.Get("Content-Type"), r.Header.Get("Authorization"), r.Header.Get("Cookie"), scheme+"://"+r.Host+r.URL.RequestURI())
        if status == 401 {{ w.Header().Set("WWW-Authenticate", "Bearer") }}
        if status == 204 {{ w.WriteHeader(status); return }}
        w.Header().Set("Content-Type", "application/json"); w.WriteHeader(status)
        if r.Method != "HEAD" {{ _ = json.NewEncoder(w).Encode(body) }}
    }})
    {setup}
    return app
}}"""
    if authenticated:
        adapter = adapter.replace(
            'c.Get("Authorization")',
            'strings.Join(c.GetReqHeaders()["Authorization"], ", ")',
        ).replace(
            'r.Header.Get("Authorization")',
            'strings.Join(r.Header.Values("Authorization"), ", ")',
        )
    http_import = '"net/http"; "io"; "encoding/json";' if target != "fiber" else '"time";'
    if authenticated:
        http_import += ' "strings";'
    result["app.go"] = f'''// SPDX-License-Identifier: Apache-2.0
package backend
import ({http_import} "{MODULES[target]}"; "github.com/jackc/pgx/v5/pgxpool")
{adapter}
'''
    code = GO_DRF
    if authenticated:
        from .jwt_security import go_access_principal

        code = code.replace(
            '    "encoding/json"',
            '    "encoding/json"\n    "encoding/base64"\n    "os"\n    "regexp"\n    "time"\n    "github.com/golang-jwt/jwt/v5"',
        )
        code = code.replace("AUTHORIZATION_GUARD", "")
        code = code.replace(
            "AUTHORIZATION_CHECK",
            'principal:=map[string]string{}\n    if view.Authentication != "" { var status int; principal,status=accessPrincipal(authorization,method,path);if status!=0 {\n'
            '        message:=map[int]string{401:"not authenticated",403:"permission denied",503:"authentication unavailable"}[status]\n'
            '        return status,map[string]string{"detail":message}\n    } }',
        )
        code += go_access_principal("")
    else:
        code = code.replace(
            "AUTHORIZATION_GUARD",
            'if authorization!="" || strings.Contains(cookie,"sessionid=") { return 501,map[string]string{"detail":"Authentication requires a separately qualified migration profile."} }',
        ).replace("AUTHORIZATION_CHECK", "principal:=map[string]string{}")
    if not sqlite:
        code = code.replace(
            '"UPDATE migration_identity SET value=value+1 WHERE table_name=$1 RETURNING value"',
            "\"SELECT nextval(pg_get_serial_sequence($1, 'id'))\"",
        )
    result["drf.go"] = code + DRF_HELPERS
    return result


GO_DRF = r"""// SPDX-License-Identifier: Apache-2.0
package backend
import (
    "bytes"
    "context"
    _ "embed"
    "encoding/json"
    "errors"
    "fmt"
    "math"
    "math/big"
    "net/url"
    "sort"
    "strconv"
    "strings"
    "unicode"
    "unicode/utf8"
    "github.com/jackc/pgx/v5"
    "github.com/jackc/pgx/v5/pgxpool"
)

//go:embed contract.json
var drfContractJSON []byte
var errInvalidWrite = errors.New("invalid write")

type drfField struct {
    Name string `json:"name"`
    Kind string `json:"kind"`
    GoType string `json:"go_type"`
    SQLType string `json:"sql_type"`
    Primary bool `json:"primary_key"`
    ReadOnly bool `json:"read_only"`
    Unique bool `json:"unique"`
    Blank bool `json:"blank"`
    Required bool `json:"required"`
    Default json.RawMessage `json:"default"`
    Minimum *int64 `json:"minimum"`
    Maximum *int64 `json:"maximum"`
    Choices []string `json:"choices"`
    Forbidden *string `json:"forbidden"`
    ForbiddenError string `json:"forbidden_error"`
}
type drfModel struct {
    SourceName string `json:"source_name"`
    Name string `json:"name"`
    Table string `json:"table"`
    Fields []drfField `json:"fields"`
}
type drfSerializer struct {
    Model string `json:"model"`
    Fields []drfField `json:"fields"`
    Nested *drfNested `json:"nested"`
}
type drfNested struct {
    Name string `json:"name"`
    ForeignKey string `json:"foreign_key"`
    Serializer drfSerializer `json:"serializer"`
    Aggregate struct { Field string `json:"field"`; Limit int64 `json:"limit"`; Error map[string]any `json:"error"` } `json:"aggregate"`
}
type drfQuery struct {
    Filters map[string]any `json:"filters"`
    Ordering []string `json:"ordering"`
    OrderingFields []string `json:"ordering_fields"`
    Pagination bool `json:"pagination"`
    PageSize int64 `json:"page_size"`
}
type drfView struct { Path string `json:"path"`; Serializer drfSerializer `json:"serializer"`; Query drfQuery `json:"query"`; ReadOnly bool `json:"read_only"`; Authentication string `json:"authentication"`; Scope map[string]string `json:"scope"`; Actions []struct { Name string `json:"name"`; Kind string `json:"kind"` } `json:"actions"` }
type drfContract struct {
    Models []drfModel `json:"models"`
    Project struct { Views []drfView `json:"views"`; Database struct { Engine string `json:"engine"` } `json:"database"` } `json:"drf_project"`
}
var drfSchema = func() drfContract {
    var c drfContract
    if err := json.Unmarshal(drfContractJSON, &c); err != nil { panic(err) }
    return c
}()
func drfModelFor(name string) drfModel {
    for _, model := range drfSchema.Models { if model.Name == name { return model } }
    panic("unknown captured model")
}
func quoted(name string) string { return `"` + strings.ReplaceAll(name, `"`, `""`) + `"` }
func drfType(raw []byte) string {
    raw = bytes.TrimSpace(raw)
    if len(raw)==0 { return "NoneType" }
    switch raw[0] { case '[': return "list"; case '{': return "dict"; case '"': return "str"; case 't','f': return "bool"; case 'n': return "NoneType" }
    if bytes.ContainsAny(raw,".eE") { return "float" }; return "int"
}
func drfMessages(message string) []string { return []string{message} }

// ChoiceField uses Python str(), including repr() for members of containers.
func drfChoiceText(decoder *json.Decoder, nested bool) (string,error) {
    token,err:=decoder.Token();if err!=nil { return "",err }
    switch value:=token.(type) {
    case nil: return "None",nil
    case bool: if value { return "True",nil };return "False",nil
    case json.Number:
        text:=string(value)
        if strings.ContainsAny(text,".eE") {
            number,err:=strconv.ParseFloat(text,64);if err!=nil && !math.IsInf(number,0) { return "",err }
            if math.IsInf(number,1) { return "inf",nil };if math.IsInf(number,-1) { return "-inf",nil }
            format:=byte('g');if number==0 || math.Abs(number)>=1e-4 && math.Abs(number)<1e16 { format='f' }
            text=strconv.FormatFloat(number,format,-1,64)
            if !strings.ContainsAny(text,".e") { text+=".0" }
        }
        return text,nil
    case string:
        if !nested { return value,nil }
        quote:=rune('\'');if strings.ContainsRune(value,'\'') && !strings.ContainsRune(value,'"') { quote='"' }
        var text strings.Builder;text.WriteRune(quote)
        for _,r:=range value {
            switch {
            case r==quote || r==92: text.WriteByte(92);text.WriteRune(r)
            case r=='\n': text.WriteString(`\n`)
            case r=='\r': text.WriteString(`\r`)
            case r=='\t': text.WriteString(`\t`)
            case unicode.IsPrint(r): text.WriteRune(r)
            case r<=255: fmt.Fprintf(&text,`\x%02x`,r)
            case r<=65535: fmt.Fprintf(&text,`\u%04x`,r)
            default: fmt.Fprintf(&text,`\U%08x`,r)
            }
        };text.WriteRune(quote);return text.String(),nil
    case json.Delim:
        parts:=[]string{}
        if value=='[' {
            for decoder.More() { item,err:=drfChoiceText(decoder,true);if err!=nil { return "",err };parts=append(parts,item) }
            _,err:=decoder.Token();return "["+strings.Join(parts,", ")+"]",err
        }
        if value=='{' {
            keys:=[]string{};members:=map[string]string{}
            for decoder.More() {
                key,err:=drfChoiceText(decoder,true);if err!=nil { return "",err }
                item,err:=drfChoiceText(decoder,true);if err!=nil { return "",err }
                if _,exists:=members[key];!exists { keys=append(keys,key) };members[key]=item
            }
            for _,key:=range keys { parts=append(parts,key+": "+members[key]) }
            _,err:=decoder.Token();return "{"+strings.Join(parts,", ")+"}",err
        }
    }
    return "",errInvalidWrite
}

func drfValidate(raw []byte, schema drfSerializer, partial bool) (map[string]any, map[string]any) {
    data, invalid := map[string]json.RawMessage{}, map[string]any{}
    if len(bytes.TrimSpace(raw)) == 0 { raw = []byte("{}") }
    if err := json.Unmarshal(raw, &data); err != nil || data == nil {
        return nil, map[string]any{"non_field_errors":drfMessages("Invalid data. Expected a dictionary, but got " + drfType(raw) + ".")}
    }
    values := map[string]any{}
    for _, field := range schema.Fields {
        if field.Primary || field.ReadOnly { continue }
        input, present := data[field.Name]
        if !present {
            if partial { continue }
            if field.Required { invalid[field.Name]=drfMessages("This field is required.") }; continue
        }
        if bytes.Equal(bytes.TrimSpace(input), []byte("null")) { invalid[field.Name]=drfMessages("This field may not be null."); continue }
        var value any
        message := ""
        switch field.GoType {
        case "string":
            text, err := drfString(input)
            if len(field.Choices)>0 {
                decoder:=json.NewDecoder(bytes.NewReader(input));decoder.UseNumber()
                text,err=drfChoiceText(decoder,false)
            }
            if len(field.Choices)==0 { text = strings.TrimFunc(text,func(r rune) bool { return unicode.IsSpace(r) || r>=0x1c && r<=0x1f }) }
            if err != nil { message="Not a valid string." } else if text=="" && !field.Blank && len(field.Choices)==0 { message="This field may not be blank." } else {
                length := 0; _, _ = fmt.Sscanf(field.SQLType,"varchar(%d)",&length)
                if length>0 && utf8.RuneCountInString(text)>length { message=fmt.Sprintf("Ensure this field has no more than %d characters.",length) }
                if strings.ContainsRune(text,0) { message="Null characters are not allowed." }
                if len(field.Choices)>0 {
                    found:=false; for _, choice:=range field.Choices { if choice==text { found=true } }
                    if !found { message=fmt.Sprintf(`"%s" is not a valid choice.`,text) }
                }
                if message=="" && field.Forbidden!=nil && text==*field.Forbidden { message=field.ForbiddenError }
                value=text
            }
        case "int32", "int64":
            number,err:=drfInt(input,64)
            if err!=nil {
                message="A valid integer is required."
                text,textErr:=drfString(input)
                if textErr==nil && utf8.RuneCountInString(text)<=1000 {
                    text=strings.TrimSpace(text)
                    if dot:=strings.IndexByte(text,'.');dot>=0 && strings.Trim(text[dot+1:],"0")=="" { text=text[:dot] }
                    integer,valid:=new(big.Int).SetString(text,10)
                    if !valid && len(input)>0 && input[0]!='"' {
                        floating,parseErr:=strconv.ParseFloat(text,64)
                        if parseErr==nil && !math.IsInf(floating,0) && !math.IsNaN(floating) && math.Trunc(floating)==floating { integer,_=big.NewFloat(floating).Int(nil);valid=true }
                    }
                    if valid {
                        if field.Minimum!=nil && integer.Cmp(big.NewInt(*field.Minimum))<0 { message=fmt.Sprintf("Ensure this value is greater than or equal to %d.",*field.Minimum) }
                        if field.Maximum!=nil && integer.Cmp(big.NewInt(*field.Maximum))>0 { message=fmt.Sprintf("Ensure this value is less than or equal to %d.",*field.Maximum) }
                    }
                }
            } else if field.Minimum!=nil && number<*field.Minimum { message=fmt.Sprintf("Ensure this value is greater than or equal to %d.",*field.Minimum) } else if field.Maximum!=nil && number>*field.Maximum { message=fmt.Sprintf("Ensure this value is less than or equal to %d.",*field.Maximum) } else { value=number }
        case "bool":
            flag,err:=drfBool(input); if err!=nil { message="Must be a valid boolean." } else { value=flag }
        case "DecimalValue":
            precision,scale:=0,0; _,_ = fmt.Sscanf(field.SQLType,"numeric(%d,%d)",&precision,&scale)
            number,err:=nativeDecimal(input,precision,scale,true)
            if err!=nil { message="A valid number is required."; if strings.HasPrefix(err.Error(),"Ensure that ") { message=err.Error() } } else { value=string(number) }
        default: message="Unsupported field."
        }
        if message!="" { invalid[field.Name]=drfMessages(message) } else { values[field.Name]=value }
    }
    if nested:=schema.Nested; nested!=nil {
        input,present:=data[nested.Name]
        if !present { if !partial { invalid[nested.Name]=drfMessages("This field is required.") } } else if bytes.Equal(bytes.TrimSpace(input),[]byte("null")) {
            invalid[nested.Name]=drfMessages("This field may not be null.")
        } else {
            var items []json.RawMessage
            if err:=json.Unmarshal(input,&items);err!=nil || items==nil { invalid[nested.Name]=map[string]any{"non_field_errors":drfMessages(fmt.Sprintf(`Expected a list of items but got type "%s".`,drfType(input)))} } else {
                children:=[]map[string]any{}; childErrors:=map[string]any{}; bad:=false
                for i,item:=range items { child,errors:=drfValidate(item,nested.Serializer,partial); if bytes.Equal(bytes.TrimSpace(item),[]byte("null")) { childErrors[strconv.Itoa(i)]=drfMessages("This field may not be null.");bad=true;continue }; children=append(children,child);if len(errors)>0 { childErrors[strconv.Itoa(i)]=errors;bad=true } }
                if bad { invalid[nested.Name]=childErrors } else { values[nested.Name]=children }
            }
        }
    }
    return values,invalid
}

func drfRows(ctx context.Context, tx pgx.Tx, schema drfSerializer, where string, args ...any) ([]map[string]any,error) {
    return drfQueryRows(ctx,tx,schema,where," ORDER BY id",args...)
}
func drfQueryRows(ctx context.Context, tx pgx.Tx, schema drfSerializer, where, tail string, args ...any) ([]map[string]any,error) {
    model:=drfModelFor(schema.Model)
    columns:=[]string{}
    for _,f:=range schema.Fields { columns=append(columns,quoted(f.Name)+"::text") }
    rows,err:=tx.Query(ctx,"SELECT "+strings.Join(columns,",")+" FROM "+quoted(model.Table)+where+tail,args...)
    if err!=nil { return nil,err }
    result:=[]map[string]any{}
    for rows.Next() {
        values,err:=rows.Values();if err!=nil { rows.Close();return nil,err }
        item:=map[string]any{}
        for i,field:=range schema.Fields {
            if values[i]==nil { item[field.Name]=nil;continue }
            text:=values[i].(string)
            switch field.GoType {
            case "int32","int64": number,err:=strconv.ParseInt(text,10,64);if err!=nil { rows.Close();return nil,err };item[field.Name]=number
            case "bool": item[field.Name]=text=="true" || text=="t"
            default: item[field.Name]=text
            }
        }
        result=append(result,item)
    }
    err=rows.Err();rows.Close();if err!=nil { return nil,err }
    if nested:=schema.Nested;nested!=nil {
        for _,item:=range result {
            children,err:=drfRows(ctx,tx,nested.Serializer," WHERE "+quoted(nested.ForeignKey)+"=$1",item["id"])
            if err!=nil { return nil,err };item[nested.Name]=children
        }
    }
    return result,nil
}

func drfUnique(ctx context.Context, tx pgx.Tx, schema drfSerializer, values map[string]any, id int64) (map[string]any,error) {
    invalid:=map[string]any{};model:=drfModelFor(schema.Model)
    for _,field:=range schema.Fields {
        value,present:=values[field.Name];if !field.Unique || !present { continue }
        var found bool
        if err:=tx.QueryRow(ctx,"SELECT EXISTS (SELECT 1 FROM "+quoted(model.Table)+" WHERE "+quoted(field.Name)+"=$1 AND id<>$2)",value,id).Scan(&found);err!=nil { return nil,err }
        if found { invalid[field.Name]=drfMessages(strings.ToLower(model.SourceName)+" with this "+strings.ReplaceAll(field.Name,"_"," ")+" already exists.") }
    }
    return invalid,nil
}

func drfInsert(ctx context.Context, tx pgx.Tx, model drfModel, values map[string]any) (int64,error) {
    // SQLite AUTOINCREMENT rolls back with the write. PostgreSQL sequences do
    // not; a transactional counter retains source identity behavior on failures.
    var id int64
    if err:=tx.QueryRow(ctx,"UPDATE migration_identity SET value=value+1 WHERE table_name=$1 RETURNING value",model.Table).Scan(&id);err!=nil { return 0,err }
    names,args,slots:=[]string{quoted("id")},[]any{id},[]string{"$1"}
    for _,field:=range model.Fields {
        if field.Primary { continue }
        value,present:=values[field.Name]
        if !present {
            if len(field.Default)>0 { decoder:=json.NewDecoder(bytes.NewReader(field.Default));decoder.UseNumber();if err:=decoder.Decode(&value);err!=nil{return 0,err} } else if field.GoType=="string" { value="" } else { return 0,fmt.Errorf("missing model value") }
        }
        if n,ok:=value.(json.Number);ok { value=string(n) }
        names=append(names,quoted(field.Name));args=append(args,value);slots=append(slots,fmt.Sprintf("$%d",len(args)))
    }
    _,err:=tx.Exec(ctx,"INSERT INTO "+quoted(model.Table)+" ("+strings.Join(names,",")+") VALUES ("+strings.Join(slots,",")+")",args...)
    return id,err
}

func drfWhere(query drfQuery, scope map[string]string, principal map[string]string) (string,[]any) {
    names:=[]string{};for name:=range query.Filters { names=append(names,name) };sort.Strings(names)
    terms,args:=[]string{},[]any{}
    for _,name:=range names { args=append(args,query.Filters[name]);terms=append(terms,quoted(name)+fmt.Sprintf("=$%d",len(args))) }
    names=names[:0];for name:=range scope { names=append(names,name) };sort.Strings(names)
    for _,name:=range names { args=append(args,principal[scope[name]]);terms=append(terms,quoted(name)+fmt.Sprintf("=$%d",len(args))) }
    if len(terms)==0 { return "",args };return " WHERE "+strings.Join(terms," AND "),args
}
func drfParams(raw string) url.Values {
    values:=url.Values{}
    for _,pair:=range strings.Split(raw,"&") { if pair!="" { key,value,_:=strings.Cut(pair,"=");values.Add(queryDecode(key),queryDecode(value)) } }
    return values
}
func drfPositive(text string, fallback int64, strict bool) *big.Int {
    // Python int accepts Unicode decimal digits and separators between digits.
    text=strings.TrimSpace(text);var normalized strings.Builder;previousDigit:=false;valid:=true;digits:=0
    for i,r:=range text {
        if i==0 && (r=='+' || r=='-') { normalized.WriteRune(r);continue }
        if r=='_' { if !previousDigit { valid=false };previousDigit=false;continue }
        value:=-1
        if r>='0' && r<='9' { value=int(r-'0') } else {
            for _,group:=range unicode.Nd.R16 { if r>=rune(group.Lo) && r<=rune(group.Hi) && (r-rune(group.Lo))%rune(group.Stride)==0 { value=int((r-rune(group.Lo))/rune(group.Stride))%10;break } }
            if value<0 { for _,group:=range unicode.Nd.R32 { if r>=rune(group.Lo) && r<=rune(group.Hi) && (r-rune(group.Lo))%rune(group.Stride)==0 { value=int((r-rune(group.Lo))/rune(group.Stride))%10;break } } }
        }
        if value<0 { valid=false;break };normalized.WriteByte(byte('0'+value));digits++;previousDigit=true
    }
    number,ok:=new(big.Int).SetString(normalized.String(),10)
    if !valid || !previousDigit || digits>4300 || !ok || number.Sign()<0 || strict && number.Sign()==0 { return big.NewInt(fallback) };return number
}
func drfList(ctx context.Context, tx pgx.Tx, view drfView, address, where string, args []any) (any,error) {
    parsed,err:=url.Parse(address);if err!=nil { return nil,err }
    ordering:=view.Query.Ordering;if len(ordering)==0 { ordering=[]string{"id"} }
    requested:=[]string{}
    for _,part:=range strings.Split(queryValue(parsed.RawQuery,"ordering",""),",") {
        field:=strings.TrimSpace(part);for _,allowed:=range view.Query.OrderingFields {
            if strings.TrimPrefix(field,"-")==allowed { requested=append(requested,field);break }
        }
    };if len(requested)>0 { ordering=requested }
    terms:=[]string{};model:=drfModelFor(view.Serializer.Model)
    for _,field:=range ordering {
        name:=strings.TrimPrefix(field,"-");term:=quoted(name)
        if drfSchema.Project.Database.Engine=="sqlite" { for _,f:=range model.Fields { if f.Name==name && f.GoType=="string" { term+=` COLLATE "C"` } } }
        if strings.HasPrefix(field,"-") { term+=" DESC" };terms=append(terms,term)
    };tail:=" ORDER BY "+strings.Join(terms,",")
    limit:=drfPositive(queryValue(parsed.RawQuery,"limit",""),view.Query.PageSize,true)
    if !view.Query.Pagination || limit.Sign()==0 { return drfQueryRows(ctx,tx,view.Serializer,where,tail,args...) }
    offset:=drfPositive(queryValue(parsed.RawQuery,"offset",""),0,false)
    var count int64
    if err:=tx.QueryRow(ctx,"SELECT COUNT(*) FROM "+quoted(model.Table)+where,args...).Scan(&count);err!=nil { return nil,err }
    rows:=[]map[string]any{}
    if offset.Cmp(big.NewInt(count))<0 {
        if !limit.IsInt64() { return nil,fmt.Errorf("pagination exceeds database integer range") }
        size:=limit.Int64()
        paged:=append(append([]any{},args...),size,offset.Int64())
        rows,err=drfQueryRows(ctx,tx,view.Serializer,where,tail+fmt.Sprintf(" LIMIT $%d OFFSET $%d",len(args)+1,len(args)+2),paged...)
        if err!=nil { return nil,err }
    }
    link:=func(position *big.Int, omitZero bool) string {
        target:=*parsed;query:=drfParams(parsed.RawQuery);query.Set("limit",limit.String())
        if omitZero && position.Sign()<=0 { query.Del("offset") } else { query.Set("offset",position.String()) }
        target.RawQuery=query.Encode();return target.String()
    }
    var next,previous any
    end:=new(big.Int).Add(offset,limit)
    if end.Cmp(big.NewInt(count))<0 { next=link(end,false) }
    if offset.Sign()>0 { previous=link(new(big.Int).Sub(offset,limit),true) }
    return map[string]any{"count":count,"next":next,"previous":previous,"results":rows},nil
}

func drfRequest(ctx context.Context,pool *pgxpool.Pool,method,path string,raw []byte,accept,contentType,authorization,cookie string, requestURL ...string) (int,any) {
    if accept!="" && accept!="*/*" && !strings.Contains(accept,"application/json") { return 406,map[string]string{"detail":"Could not satisfy the request Accept header."} }
    AUTHORIZATION_GUARD
    var view *drfView;id:=int64(0);detail:=false;action:=""
    for i:=range drfSchema.Project.Views {
        candidate:=&drfSchema.Project.Views[i]
        if path==candidate.Path { view=candidate;break }
        for _,item:=range candidate.Actions { if path==candidate.Path+item.Name+"/" { view=candidate;action=item.Kind;break } }
        if view!=nil { break }
        if strings.HasPrefix(path,candidate.Path) && strings.HasSuffix(path,"/") {
            part:=strings.TrimSuffix(strings.TrimPrefix(path,candidate.Path),"/")
            parsed,err:=strconv.ParseInt(part,10,64);if err==nil && parsed>=0 && !strings.ContainsAny(part,"+-/") { view=candidate;id=parsed;detail=true;break }
        }
    }
    if view==nil { return 404,map[string]string{"detail":"Not found."} }
    AUTHORIZATION_CHECK
    actualMethod:=method;if method=="HEAD" { actualMethod="GET" }
    allowed:=action!="" && actualMethod=="GET" || action=="" && (actualMethod=="GET" || !view.ReadOnly && (actualMethod=="POST" && !detail || detail && (actualMethod=="PUT" || actualMethod=="PATCH" || actualMethod=="DELETE")))
    if !allowed { return 405,map[string]string{"detail":fmt.Sprintf(`Method "%s" not allowed.`,method)} }
    tx,err:=pool.Begin(ctx);if err!=nil { return 500,map[string]string{"detail":"Database unavailable."} };defer tx.Rollback(ctx)
    schema:=view.Serializer;model:=drfModelFor(schema.Model)
    where,args:=drfWhere(view.Query,view.Scope,principal)
    if action=="count" { var count int64;if err=tx.QueryRow(ctx,"SELECT COUNT(*) FROM "+quoted(model.Table)+where,args...).Scan(&count);err!=nil { return 500,map[string]string{"detail":"Database read failed."} };return 200,map[string]any{"count":count} }
    existing:=[]map[string]any{}
    if detail {
        if where=="" { where=" WHERE " } else { where+=" AND " };args=append(args,id)
        where+=fmt.Sprintf("id=$%d",len(args))
        existing,err=drfRows(ctx,tx,schema,where,args...)
        if err!=nil { return 500,map[string]string{"detail":"Database read failed."} }
        if len(existing)==0 { return 404,map[string]string{"detail":"No "+model.SourceName+" matches the given query."} }
    }
    if actualMethod=="GET" {
        if detail { return 200,existing[0] }
        address:="http://testserver"+path;if len(requestURL)>0 { address=requestURL[0] }
        items,err:=drfList(ctx,tx,*view,address,where,args);if err!=nil { return 500,map[string]string{"detail":"Database read failed."} };return 200,items
    }
    if actualMethod=="DELETE" {
        if _,err=tx.Exec(ctx,"DELETE FROM "+quoted(model.Table)+where,args...);err!=nil { return 500,map[string]string{"detail":"Database write failed."} }
        if err=tx.Commit(ctx);err!=nil { return 500,map[string]string{"detail":"Database write failed."} };return 204,nil
    }
    if len(raw)>0 && !strings.HasPrefix(contentType,"application/json") { return 415,map[string]string{"detail":fmt.Sprintf(`Unsupported media type "%s" in request.`,contentType)} }
    if len(raw)>0 && !json.Valid(raw) { return 400,map[string]string{"detail":"JSON parse error"} }
    values,invalid:=drfValidate(raw,schema,actualMethod=="PATCH")
    unique,err:=drfUnique(ctx,tx,schema,values,id);if err!=nil { return 500,map[string]string{"detail":"Database read failed."} }
    for key,value:=range unique { invalid[key]=value };if len(invalid)>0 { return 400,invalid }
    if !detail {
        for field,claim:=range view.Scope { values[field]=principal[claim] }
        id,err=drfInsert(ctx,tx,model,values)
        if err==nil && schema.Nested!=nil {
            nested:=schema.Nested;total:=int64(0)
            for _,child:=range values[nested.Name].([]map[string]any) {
                child[nested.ForeignKey]=id
                _,err=drfInsert(ctx,tx,drfModelFor(nested.Serializer.Model),child);if err!=nil { break }
                count:=child[nested.Aggregate.Field].(int64)
                if count>0 && total>math.MaxInt64-count { return 400,nested.Aggregate.Error };total+=count
            }
            if err==nil && total>nested.Aggregate.Limit { return 400,nested.Aggregate.Error }
        }
    } else {
        sets,updateArgs:=[]string{},append([]any{},args...)
        for _,field:=range schema.Fields {
            if field.Primary || field.ReadOnly { continue };value,present:=values[field.Name];if !present { continue }
            updateArgs=append(updateArgs,value);sets=append(sets,quoted(field.Name)+fmt.Sprintf("=$%d",len(updateArgs)))
        }
        if len(sets)>0 { _,err=tx.Exec(ctx,"UPDATE "+quoted(model.Table)+" SET "+strings.Join(sets,",")+where,updateArgs...) }
    }
    if err!=nil { return 500,map[string]string{"detail":"Database write failed."} }
    saved,err:=drfRows(ctx,tx,schema," WHERE id=$1",id);if err!=nil || len(saved)!=1 { return 500,map[string]string{"detail":"Database read failed."} }
    if err=tx.Commit(ctx);err!=nil { return 500,map[string]string{"detail":"Database write failed."} }
    if actualMethod=="POST" { return 201,saved[0] };return 200,saved[0]
}
"""
