# SPDX-License-Identifier: Apache-2.0
"""Flat PostgreSQL schema baselines and bounded reads for the axum target."""

from __future__ import annotations

import dataclasses
import json
import os
import subprocess
import uuid
from pathlib import Path
from urllib.parse import parse_qsl, urlencode

import pytest
from test_typescript_to_rust import needs_node, needs_rust, request

from sanka_extension_typescript_to_rust.adapter import handle
from sanka_extension_typescript_to_rust.capture import capture, configuration
from sanka_extension_typescript_to_rust.schema import capture_tables
from sanka_extensions.code import ExtensionRequest

SCHEMA_SQL = """-- Flat catalogue schema
CREATE TABLE widgets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL UNIQUE,
    quantity bigint NOT NULL,
    note text,
    active boolean NOT NULL
);

CREATE TABLE "orders" (
    "id" bigserial PRIMARY KEY,
    "reference" text NOT NULL,
    "total" bigint
);
"""
MODELS_TS = """export interface Widget {
  id: number;
  name: string;
  quantity: number;
  note: string | null;
  active: boolean;
}

export type Order = {
  id: number;
  reference: string;
  total: number | null;
};
"""
WIDGETS_SQL = "SELECT id, name, quantity, note, active FROM widgets ORDER BY id LIMIT $1"
ORDERS_SQL = 'SELECT "id", "reference", "total" FROM "orders" ORDER BY "id" LIMIT $1'
POOL = "const pool = new Pool({ connectionString: process.env.DATABASE_URL });"
PACKAGE_JSON = json.dumps(
    {"name": "fixture", "private": True, "dependencies": {"express": "^5.2.1", "pg": "^8.23.0"}}
)
DATABASE = {"source_framework": "express", "target_framework": "axum", "database_layer": "sqlx"}
needs_postgres = pytest.mark.skipif(
    not os.getenv("SANKA_MIGRATE_TEST_POSTGRES_DSN"),
    reason="requires an explicit SANKA_MIGRATE_TEST_POSTGRES_DSN",
)


def app_source(
    *,
    widgets_sql: str = WIDGETS_SQL,
    widgets_limit: str = "100",
    pool: str = POOL,
    pg_import: str = 'import { Pool } from "pg";',
    respond: str = "res.json(rows);",
) -> str:
    return (
        'import express from "express";\n'
        f"{pg_import}\n"
        'import type { Widget } from "./models";\n\n'
        "const app = express();\n"
        f"{pool}\n\n"
        'app.get("/health", (_req, res) => {\n  res.json({ ok: true });\n});\n\n'
        'app.get("/widgets", async (_req, res) => {\n'
        f"  const {{ rows }} = await pool.query({json.dumps(widgets_sql)}, [{widgets_limit}]);\n"
        f"  {respond}\n"
        "});\n\n"
        'app.get("/orders", async (req, res) => {\n'
        f"  const {{ rows }} = await pool.query({json.dumps(ORDERS_SQL)}, [5]);\n"
        "  return res.json(rows);\n"
        "});\n\n"
        "export default app;\n"
    )


def project(
    root: Path,
    *,
    schema: str = SCHEMA_SQL,
    models: str | None = MODELS_TS,
    app: str | None = None,
) -> Path:
    (root / "src").mkdir(exist_ok=True)
    (root / "src" / "app.ts").write_text(app_source() if app is None else app)
    models_path = root / "src" / "models.ts"
    if models is None:
        models_path.unlink(missing_ok=True)
    else:
        models_path.write_text(models)
    (root / "schema.sql").write_text(schema)
    (root / "package.json").write_text(PACKAGE_JSON)
    return root


def database_request(root: Path, command: str = "plan") -> ExtensionRequest:
    return dataclasses.replace(request(root), command=command, configuration=dict(DATABASE))


def apply(root: Path) -> Path:
    req = database_request(root)
    planned = handle(req)
    assert planned.outcome == "success", planned.error
    assert planned.data["capture"]["gaps"] == []
    result = handle(
        dataclasses.replace(
            req,
            command="apply",
            reviewed_plan_hash="runtime-reviewed-plan",
            configuration=req.configuration | {"extension_plan_hash": planned.data["plan_hash"]},
        )
    )
    assert result.outcome == "success", result.error
    return Path(str(result.data["output"]))


def gaps(root: Path, config: dict[str, str] | None = None) -> list[str]:
    return list(capture(root, configuration(dict(DATABASE) if config is None else config))["gaps"])


def schema_dsn(dsn: str, schema: str) -> str:
    """Pin one schema through ``options=-csearch_path=...`` without touching the rest of the URL."""
    base, _, query = dsn.partition("?")
    pairs = [(key, value) for key, value in parse_qsl(query) if key != "options"]
    pairs.append(("options", "-csearch_path=" + schema))
    return base + "?" + urlencode(pairs)


def test_configuration_boundaries() -> None:
    plain = configuration({})
    assert plain["database_layer"] == "none"
    assert "schema_file" not in plain
    full = configuration({"database_layer": "sqlx"})
    assert full["schema_file"] == "schema.sql"
    assert full["models_file"] == "src/models.ts"
    assert (full["database_dialect"], full["migration_tool"], full["schema_mode"]) == (
        "postgresql",
        "sqlx",
        "empty",
    )
    for config in (
        {"database_layer": "diesel"},
        {"database_layer": "sqlx", "database_dialect": "mysql"},
        {"database_layer": "sqlx", "migration_tool": "refinery"},
        {"database_layer": "sqlx", "schema_mode": "existing"},
        {"database_layer": "sqlx", "schema_file": "../schema.sql"},
        {"database_layer": "sqlx", "schema_file": "schema.txt"},
        {"database_layer": "sqlx", "models_file": "src/app.ts"},
        {"schema_file": "schema.sql"},
        {"database_layer": 1},
    ):
        with pytest.raises(ValueError):
            configuration(config)


@pytest.mark.parametrize(
    "ddl",
    [
        "CREATE TABLE widgets (id integer PRIMARY KEY, name text DEFAULT 'x')",
        "CREATE TABLE widgets (id integer PRIMARY KEY, owner integer REFERENCES users(id))",
        "CREATE TABLE widgets (id integer, name text, PRIMARY KEY (id))",
        "CREATE TABLE widgets (id integer PRIMARY KEY, name varchar)",
        "CREATE TABLE widgets (id integer PRIMARY KEY, other integer PRIMARY KEY)",
        "CREATE TABLE widgets (id integer PRIMARY KEY, counter serial)",
        "CREATE TABLE widgets (id text PRIMARY KEY)",
        "CREATE TABLE widgets (id integer PRIMARY KEY, price numeric(10, 2))",
        "CREATE TABLE widgets (id integer NOT NULL)",
        "CREATE TABLE Widgets (id integer PRIMARY KEY)",
        "CREATE TABLE widgets (id integer PRIMARY KEY, type text)",
        "CREATE TABLE widgets (id integer PRIMARY KEY); CREATE INDEX widgets_id ON widgets (id)",
        "CREATE TABLE _sqlx_migrations (id integer PRIMARY KEY)",
        "",
    ],
)
def test_schema_capture_rejects_unsupported_ddl(tmp_path: Path, ddl: str) -> None:
    path = tmp_path / "schema.sql"
    path.write_text(ddl)
    with pytest.raises(ValueError):
        capture_tables(path)


@needs_node
def test_database_plan_and_generated_layer(tmp_path: Path) -> None:
    project(tmp_path)
    plan = handle(database_request(tmp_path))
    assert plan.outcome == "success", plan.error
    captured = plan.data["capture"]
    assert captured["gaps"] == []
    assert [(model["name"], model["table"]) for model in captured["models"]] == [
        ("Order", "orders"),
        ("Widget", "widgets"),
    ]
    widget = captured["models"][1]
    assert [
        (field["name"], field["sql_type"], field["rust_type"], field["nullable"], field["identity"])
        for field in widget["fields"]
    ] == [
        ("id", "integer", "i32", False, "by default"),
        ("name", "varchar(40)", "String", False, None),
        ("quantity", "bigint", "i64", False, None),
        ("note", "text", "String", True, None),
        ("active", "boolean", "bool", False, None),
    ]
    assert captured["models"][0]["fields"][0]["identity"] == "serial"
    assert [(route["path"], route.get("read")) for route in captured["routes"]] == [
        ("/health", None),
        ("/orders", {"model": "Order", "table": "orders", "order_by": "id", "limit": 5}),
        ("/widgets", {"model": "Widget", "table": "widgets", "order_by": "id", "limit": 100}),
    ]
    files = plan.data["files"]
    assert {
        "src/models.rs",
        "src/bin/migrate.rs",
        "migrations/0001_initial.up.sql",
        "migrations/0001_initial.down.sql",
        ".env.example",
    } <= set(files)
    assert 'name = "sqlx"' in files["Cargo.lock"]
    assert "sqlx = {" in files["Cargo.toml"]
    up = files["migrations/0001_initial.up.sql"]
    assert '"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in up
    assert '"name" varchar(40) NOT NULL UNIQUE' in up
    assert '"id" bigserial PRIMARY KEY' in up
    assert "RAISE EXCEPTION" in up
    down = files["migrations/0001_initial.down.sql"]
    assert down.index('"widgets"') < down.index('"orders"')
    models = files["src/models.rs"]
    assert "pub note: Option<String>," in models
    assert 'serialize_with = "bigint_as_string"' in models
    library = files["src/lib.rs"]
    assert "State(pool): State<PgPool>" in library
    assert ".bind(100_i64)" in library
    assert (
        'r#"SELECT "id", "name", "quantity", "note", "active" FROM "widgets" '
        'ORDER BY "id" LIMIT $1"#'
    ) in library
    # The literal route keeps its original shape next to the database reads.
    assert "async fn route_0() -> impl IntoResponse" in library


@needs_node
def test_database_capture_gaps(tmp_path: Path) -> None:
    project(tmp_path)
    assert gaps(tmp_path) == []
    assert any("database_layer" in gap for gap in gaps(tmp_path, {}))
    cases = {
        "column order": app_source(
            widgets_sql="SELECT name, id, quantity, note, active FROM widgets ORDER BY id LIMIT $1"
        ),
        "ordering": app_source(
            widgets_sql=WIDGETS_SQL.replace("ORDER BY id", "ORDER BY name"),
        ),
        "unbounded": app_source(
            widgets_sql="SELECT id, name, quantity, note, active FROM widgets ORDER BY id"
        ),
        "zero limit": app_source(widgets_limit="0"),
        "large limit": app_source(widgets_limit="1001"),
        "default import": app_source(pg_import='import pg from "pg";'),
        "pool options": app_source(pool="const pool = new Pool();"),
        "wrapped response": app_source(respond="res.json({ rows });"),
    }
    for name, text in cases.items():
        project(tmp_path, app=text)
        assert gaps(tmp_path), name
    project(
        tmp_path,
        models=MODELS_TS.replace("  active: boolean;\n", "  active: boolean;\n  extra: number;\n"),
    )
    assert any("matching columns" in gap for gap in gaps(tmp_path))
    project(tmp_path, models=None)
    assert any("models_file" in gap for gap in gaps(tmp_path))
    project(tmp_path, schema=SCHEMA_SQL + "\nCREATE INDEX widgets_name ON widgets (name);\n")
    assert any("CREATE TABLE" in gap for gap in gaps(tmp_path))


@needs_node
def test_read_replay_requires_dedicated_databases(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    project(tmp_path)
    apply(tmp_path)
    for name in ("SANKA_RUST_TARGET_TEST_DATABASE_URL", "SANKA_RUST_SOURCE_TEST_DATABASE_URL"):
        monkeypatch.delenv(name, raising=False)
    # An ambient DATABASE_URL is never adopted as a test fixture.
    monkeypatch.setenv("DATABASE_URL", "postgresql://implicit@localhost/ambient")
    tested = handle(database_request(tmp_path, "test"))
    assert tested.outcome == "error"
    assert tested.error is not None
    assert "SANKA_RUST_TARGET_TEST_DATABASE_URL" in tested.error.message
    monkeypatch.setenv("SANKA_RUST_TARGET_TEST_DATABASE_URL", "sqlite:///fixture")
    rejected = handle(database_request(tmp_path, "test"))
    assert rejected.outcome == "error"
    assert rejected.error is not None
    assert "PostgreSQL" in rejected.error.message
    monkeypatch.setenv("SANKA_RUST_TARGET_TEST_DATABASE_URL", "postgresql://sanka@localhost/one")
    monkeypatch.setenv("SANKA_RUST_SOURCE_TEST_DATABASE_URL", "postgresql://sanka@localhost/one")
    verified = handle(database_request(tmp_path, "verify"))
    assert verified.outcome == "error"
    assert verified.error is not None
    assert "distinct" in verified.error.message
    assert not (tmp_path / ".sanka/rust/test.json").exists()
    assert not (tmp_path / ".sanka/rust/verify.json").exists()


@needs_node
@needs_rust
@needs_postgres
def test_migration_and_read_lifecycle(
    tmp_path: Path, node_tools: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import psycopg
    from psycopg import sql

    project(tmp_path)
    output = apply(tmp_path)
    dsn = os.environ["SANKA_MIGRATE_TEST_POSTGRES_DSN"]
    schemas = ["rust_read_" + uuid.uuid4().hex for _ in range(2)]
    source_url, target_url = (schema_dsn(dsn, schema) for schema in schemas)
    environment = os.environ | {"CARGO_TERM_COLOR": "never"}
    environment.setdefault("CARGO_TARGET_DIR", str(output.parent / "rust-target"))

    def migrate(direction: str, url: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["cargo", "run", "--locked", "--quiet", "--bin", "migrate", "--", direction],
            cwd=output,
            env=environment | {"DATABASE_URL": url},
            capture_output=True,
            text=True,
            timeout=1200,
            check=False,
        )

    def columns(url: str) -> list[tuple[object, ...]]:
        with psycopg.connect(url) as connection:
            return connection.execute(
                "SELECT table_name, column_name, ordinal_position, data_type, is_nullable, "
                "character_maximum_length, is_identity, column_default IS NOT NULL "
                "FROM information_schema.columns WHERE table_schema = current_schema() "
                "AND table_name IN ('widgets', 'orders') ORDER BY table_name, ordinal_position"
            ).fetchall()

    def constraints(url: str) -> list[tuple[object, ...]]:
        with psycopg.connect(url) as connection:
            return connection.execute(
                "SELECT table_name, constraint_type FROM information_schema.table_constraints "
                "WHERE table_schema = current_schema() AND table_name IN ('widgets', 'orders') "
                "AND constraint_type IN ('PRIMARY KEY', 'UNIQUE') ORDER BY 1, 2"
            ).fetchall()

    widgets = [
        (1, "first", 9223372036854775807, None, True),
        (2, "日本語 <tag>&", -1, "line\nbreak", False),
        (3, "third", 0, "", True),
    ]
    orders = [
        (number, f"r{number}", total)
        for number, total in enumerate([None, 9007199254740993, -5, 0, 1, 2], start=1)
    ]
    with psycopg.connect(dsn, autocommit=True) as admin:
        try:
            for schema in schemas:
                admin.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
            with psycopg.connect(source_url, autocommit=True) as connection:
                connection.execute(SCHEMA_SQL)
            applied = migrate("up", target_url)
            assert applied.returncode == 0, applied.stdout + applied.stderr
            assert migrate("up", target_url).returncode == 0
            assert columns(target_url) == columns(source_url)
            assert len(columns(target_url)) == 8
            assert constraints(target_url) == constraints(source_url)
            assert constraints(target_url) == [
                ("orders", "PRIMARY KEY"),
                ("widgets", "PRIMARY KEY"),
                ("widgets", "UNIQUE"),
            ]
            # The baseline never adopts a schema that already holds captured tables.
            blocked = migrate("up", source_url)
            assert blocked.returncode != 0
            assert "already exist" in blocked.stderr
            for url in (source_url, target_url):
                with psycopg.connect(url, autocommit=True) as connection:
                    for row in widgets:
                        connection.execute(
                            "INSERT INTO widgets (id, name, quantity, note, active) "
                            "VALUES (%s, %s, %s, %s, %s)",
                            row,
                        )
                    for order in orders:
                        connection.execute(
                            "INSERT INTO orders (id, reference, total) VALUES (%s, %s, %s)", order
                        )
            monkeypatch.setenv("SANKA_RUST_SOURCE_TEST_DATABASE_URL", source_url)
            monkeypatch.setenv("SANKA_RUST_TARGET_TEST_DATABASE_URL", target_url)
            verified = handle(database_request(tmp_path, "verify"))
            assert verified.outcome == "success", verified.error
            expected_widgets = [
                {"id": i, "name": name, "quantity": str(quantity), "note": note, "active": active}
                for i, name, quantity, note, active in widgets
            ]
            expected_orders = [
                {"id": str(i), "reference": ref, "total": None if total is None else str(total)}
                for i, ref, total in orders[:5]
            ]
            assert [item["body"] for item in verified.data["source"]] == [
                {"ok": True},
                expected_orders,
                expected_widgets,
            ]
            assert verified.data["candidate"] == verified.data["source"]
            tested = handle(database_request(tmp_path, "test"))
            assert tested.outcome == "success", tested.error
            with psycopg.connect(target_url, autocommit=True) as connection:
                connection.execute("UPDATE widgets SET active = false WHERE id = 1")
            mismatch = handle(database_request(tmp_path, "verify"))
            assert mismatch.outcome == "error"
            assert mismatch.error is not None
            assert mismatch.error.code == "SANKA_EXTENSION_PARITY_FAILED"
            reverted = migrate("down", target_url)
            assert reverted.returncode == 0, reverted.stdout + reverted.stderr
            assert columns(target_url) == []
            with psycopg.connect(target_url) as connection:
                assert connection.execute("SELECT count(*) FROM _sqlx_migrations").fetchone() == (
                    0,
                )
            failed = handle(database_request(tmp_path, "test"))
            assert failed.outcome == "error"
            report = json.loads((tmp_path / ".sanka/rust/test.json").read_text())
            assert report["ok"] is False
            assert report["candidate"][1] == {
                "path": "/orders",
                "status": 500,
                "media_type": "application/json",
                "body": {"error": "database read failed"},
            }
            fmt = subprocess.run(
                ["cargo", "fmt", "--check"], cwd=output, capture_output=True, text=True, check=False
            )
            assert fmt.returncode == 0, fmt.stdout + fmt.stderr
        finally:
            for schema in schemas:
                admin.execute(
                    sql.SQL("DROP SCHEMA IF EXISTS {} CASCADE").format(sql.Identifier(schema))
                )
