# SPDX-License-Identifier: Apache-2.0
"""Pinned axum rendering for captured JSON GET contracts."""

from __future__ import annotations

from importlib.resources import files
from typing import Any

from .capture import canonical

RUST_VERSION = "1.93.1"
CRATE = "migrated-backend"
LIBRARY = "migrated_backend"

CARGO_TOML = f"""[package]
name = "{CRATE}"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
publish = false

[lib]
name = "{LIBRARY}"
path = "src/lib.rs"

[[bin]]
name = "{CRATE}"
path = "src/main.rs"

[dependencies]
axum = {{ version = "0.8", default-features = false, features = ["http1", "tokio", "json"] }}
tokio = {{ version = "1", features = ["rt-multi-thread", "macros", "net", "signal"] }}
serde_json = "1"

[dev-dependencies]
tower = {{ version = "0.5", features = ["util"] }}
"""

TOOLCHAIN = f"""[toolchain]
channel = "{RUST_VERSION}"
profile = "minimal"
"""

LIB_RS = """// SPDX-License-Identifier: Apache-2.0
// Generated experimental endpoint contract; not a complete backend migration.
use axum::Router;
use axum::http::{HeaderValue, StatusCode, header};
use axum::response::IntoResponse;
use axum::routing::get;

/// The captured route contract. Callers own serving, shutdown and deployment settings.
pub fn app() -> Router {
    let mut router = Router::new();
@ROUTES@
    router
}

@HANDLERS@"""

HANDLER = """async fn route_@INDEX@() -> impl IntoResponse {
    (
        @STATUS@,
        [(
            header::CONTENT_TYPE,
            HeaderValue::from_static("application/json"),
        )],
        @BODY@,
    )
}
"""

MAIN_RS = """// SPDX-License-Identifier: Apache-2.0
// Generated serving entrypoint. Bind address and port are explicit environment inputs.
use std::net::{IpAddr, SocketAddr};

#[tokio::main]
async fn main() {
    let host: IpAddr = std::env::var("HOST")
        .unwrap_or_else(|_| "127.0.0.1".to_string())
        .parse()
        .expect("HOST must be an IP address");
    let port: u16 = std::env::var("PORT")
        .ok()
        .and_then(|value| value.parse().ok())
        .unwrap_or(3000);
    let listener = tokio::net::TcpListener::bind(SocketAddr::new(host, port))
        .await
        .expect("bind the configured address");
    axum::serve(listener, migrated_backend::app())
        .with_graceful_shutdown(shutdown())
        .await
        .expect("serve");
}

async fn shutdown() {
    let _ = tokio::signal::ctrl_c().await;
}
"""

README = """# Migrated backend (experimental endpoint contract)

Generated by `sanka/typescript-to-rust` from a captured Express application.
It reproduces @COUNT@ literal JSON GET route(s); see `contract.json` for the exact
captured paths, statuses and bodies. This is not a complete backend migration.

```sh
cargo build --locked
HOST=127.0.0.1 PORT=3000 cargo run --locked
cargo test --locked
```

`rust-toolchain.toml` pins the qualified toolchain. Express defaults that are not
reproduced: case-insensitive and non-strict (trailing slash) routing, the
`X-Powered-By` and `ETag` headers, and `charset=utf-8` on `Content-Type`.
"""


def rust_string(value: str) -> str:
    escaped = []
    for character in value:
        if character == "\\":
            escaped.append("\\\\")
        elif character == '"':
            escaped.append('\\"')
        elif ord(character) < 0x20 or character == "\x7f":
            escaped.append(f"\\u{{{ord(character):x}}}")
        else:
            escaped.append(character)
    return '"' + "".join(escaped) + '"'


def render(captured: dict[str, Any]) -> dict[str, str]:
    if captured["gaps"]:
        raise ValueError("resolve source capture gaps before generation")
    target = captured["configuration"]["target_framework"]
    if target != "axum":
        raise ValueError(f"unsupported target framework: {target}")
    registrations: list[str] = []
    handlers: list[str] = []
    for index, route in enumerate(captured["routes"]):
        registrations.append(
            f"    router = router.route({rust_string(route['path'])}, get(route_{index}));"
        )
        status = (
            "StatusCode::OK"
            if route["status"] == 200
            else f'StatusCode::from_u16({route["status"]}).expect("captured status code")'
        )
        handlers.append(
            HANDLER.replace("@INDEX@", str(index))
            .replace("@STATUS@", status)
            .replace("@BODY@", rust_string(route["body_json"]))
        )
    lock = files("sanka_extension_typescript_to_rust").joinpath("locks", target)
    return {
        "Cargo.toml": CARGO_TOML,
        "Cargo.lock": lock.joinpath("Cargo.lock").read_text(),
        "rust-toolchain.toml": TOOLCHAIN,
        "src/lib.rs": LIB_RS.replace("@ROUTES@", "\n".join(registrations)).replace(
            "@HANDLERS@", "\n".join(handlers)
        ),
        "src/main.rs": MAIN_RS,
        "contract.json": canonical(captured) + "\n",
        "README.md": README.replace("@COUNT@", str(len(captured["routes"]))),
    }
