# SPDX-License-Identifier: Apache-2.0
"""Static capture of a flat PostgreSQL ``schema.sql`` and its TypeScript row interfaces.

The SQL is parsed with a strict subset grammar; the interfaces are read from the
syntax tree. Neither is executed. A table qualifies only when exactly one
interface declares the same columns with the same types and nullability.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from sanka_ts_capture import ParsedFile
from sanka_ts_capture import tree as t

IDENTIFIER = re.compile(r"[a-z][a-z0-9_]{0,62}\Z")
STRUCT = re.compile(r"[A-Z][A-Za-z0-9]*\Z")
MAX_VARCHAR = 10_485_760
# normalized SQL type -> (rust type, TypeScript type, auto-increment)
SQL_TYPES: dict[str, tuple[str, str, bool]] = {
    "integer": ("i32", "number", False),
    "int": ("i32", "number", False),
    "int4": ("i32", "number", False),
    "bigint": ("i64", "number", False),
    "int8": ("i64", "number", False),
    "serial": ("i32", "number", True),
    "bigserial": ("i64", "number", True),
    "boolean": ("bool", "boolean", False),
    "bool": ("bool", "boolean", False),
    "text": ("String", "string", False),
    "varchar": ("String", "string", False),
    "character varying": ("String", "string", False),
}
RUST_KEYWORDS = frozenset(
    {
        "as",
        "break",
        "const",
        "continue",
        "crate",
        "else",
        "enum",
        "extern",
        "false",
        "fn",
        "for",
        "if",
        "impl",
        "in",
        "let",
        "loop",
        "match",
        "mod",
        "move",
        "mut",
        "pub",
        "ref",
        "return",
        "self",
        "Self",
        "static",
        "struct",
        "super",
        "trait",
        "true",
        "type",
        "unsafe",
        "use",
        "where",
        "while",
        "async",
        "await",
        "dyn",
        "abstract",
        "become",
        "box",
        "do",
        "final",
        "macro",
        "override",
        "priv",
        "typeof",
        "unsized",
        "virtual",
        "yield",
        "try",
        "gen",
    }
)
RESERVED_STRUCTS = frozenset({"Router", "Response", "State", "PgPool", "Option", "String", "Vec"})
_COMMENT = re.compile(r"--[^\n]*")
_CREATE = re.compile(
    r'\Acreate\s+table\s+(?:if\s+not\s+exists\s+)?"?([A-Za-z_][A-Za-z0-9_]*)"?\s*\((.*)\)\Z',
    re.IGNORECASE | re.DOTALL,
)
_COLUMN_START = re.compile(r'\A"?([A-Za-z_][A-Za-z0-9_]*)"?\s+', re.DOTALL)
_TYPE = re.compile(
    r"\A(character\s+varying|varchar|integer|int4|int8|int|bigint|bigserial|serial|boolean|bool|text)"
    r"(?:\s*\(\s*(\d+)\s*\))?",
    re.IGNORECASE,
)
_CONSTRAINTS = (
    ("generated by default as identity", "by default"),
    ("generated always as identity", "always"),
    ("primary key", "primary key"),
    ("not null", "not null"),
    ("unique", "unique"),
    ("null", "null"),
)
TYPESCRIPT_TYPES = {
    "NumberKeyword": "number",
    "StringKeyword": "string",
    "BooleanKeyword": "boolean",
}


def identifier(value: str, what: str) -> str:
    if not IDENTIFIER.fullmatch(value):
        raise ValueError(
            f"{what} {value!r} must be a lowercase identifier of at most 63 characters"
        )
    return value


def capture_tables(path: Path) -> list[dict[str, Any]]:
    """Parse ``schema.sql`` into flat table records; anything unsupported raises."""
    if path.is_symlink() or not path.is_file():
        raise ValueError("schema_file must be a regular file")
    if path.stat().st_size > 256 * 1024:
        raise ValueError("schema_file exceeds the capture limit")
    text = _COMMENT.sub("", path.read_text(encoding="utf-8"))
    tables: list[dict[str, Any]] = []
    for statement in text.split(";"):
        statement = statement.strip()
        if not statement:
            continue
        match = _CREATE.match(statement)
        if match is None:
            raise ValueError("only CREATE TABLE statements with column definitions are qualified")
        table = identifier(match.group(1), "table")
        columns = [_column(item.strip(), table) for item in _split_columns(match.group(2))]
        if not columns:
            raise ValueError(f"table {table!r} declares no columns")
        if sum(column["primary_key"] for column in columns) != 1:
            raise ValueError(f"table {table!r} must declare exactly one integer primary key column")
        if len({column["name"] for column in columns}) != len(columns):
            raise ValueError(f"table {table!r} declares duplicate columns")
        tables.append({"table": table, "fields": columns})
    if not tables:
        raise ValueError("schema_file declares no tables")
    if len({table["table"] for table in tables}) != len(tables):
        raise ValueError("duplicate database table")
    return sorted(tables, key=lambda table: str(table["table"]))


def _split_columns(body: str) -> list[str]:
    items: list[str] = []
    depth = 0
    current: list[str] = []
    for character in body:
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
            if depth < 0:
                raise ValueError("unbalanced parentheses in column definitions")
        if character == "," and depth == 0:
            items.append("".join(current))
            current = []
            continue
        current.append(character)
    if depth != 0:
        raise ValueError("unbalanced parentheses in column definitions")
    items.append("".join(current))
    return [item for item in items if item.strip()]


def _column(definition: str, table: str) -> dict[str, Any]:
    start = _COLUMN_START.match(definition)
    if start is None:
        raise ValueError(f"table {table!r}: table-level constraints require additional capture")
    name = identifier(start.group(1), "column")
    rest = definition[start.end() :].strip()
    typed = _TYPE.match(rest)
    if typed is None:
        raise ValueError(f"column {table}.{name}: unsupported SQL type")
    sql_type = re.sub(r"\s+", " ", typed.group(1).lower())
    length = typed.group(2)
    rust_type, ts_type, auto = SQL_TYPES[sql_type]
    if sql_type in {"varchar", "character varying"}:
        if length is None or not 0 < int(length) <= MAX_VARCHAR:
            raise ValueError(f"column {table}.{name}: varchar requires a positive bounded length")
        sql_type = f"varchar({int(length)})"
    elif length is not None:
        raise ValueError(f"column {table}.{name}: length is only supported for varchar")
    if sql_type in {"int", "int4"}:
        sql_type = "integer"
    elif sql_type == "int8":
        sql_type = "bigint"
    elif sql_type == "bool":
        sql_type = "boolean"
    remainder = re.sub(r"\s+", " ", rest[typed.end() :].strip().lower())
    flags: dict[str, bool] = {}
    identity: str | None = "serial" if auto else None
    while remainder:
        for phrase, flag in _CONSTRAINTS:
            if remainder == phrase or remainder.startswith(phrase + " "):
                if flag in flags or (
                    flag.endswith("identity") is False and flag == "null" and "not null" in flags
                ):
                    raise ValueError(f"column {table}.{name}: duplicate or conflicting constraint")
                if flag in {"by default", "always"}:
                    if identity is not None:
                        raise ValueError(
                            f"column {table}.{name}: conflicting identity declarations"
                        )
                    identity = flag
                else:
                    flags[flag] = True
                remainder = remainder[len(phrase) :].strip()
                break
        else:
            raise ValueError(
                f"column {table}.{name}: unsupported constraint {remainder.split(' ')[0]!r}"
            )
    primary = flags.get("primary key", False)
    nullable = not primary and not flags.get("not null", False)
    if primary and rust_type not in {"i32", "i64"}:
        raise ValueError(f"column {table}.{name}: only integer primary keys are qualified")
    if identity is not None and not primary:
        raise ValueError(f"column {table}.{name}: auto increment requires the primary key")
    if identity is not None and rust_type not in {"i32", "i64"}:
        raise ValueError(f"column {table}.{name}: identity requires an integer column")
    if name in RUST_KEYWORDS:
        raise ValueError(f"column {table}.{name}: name is a Rust keyword")
    return {
        "name": name,
        "sql_type": sql_type,
        "rust_type": rust_type,
        "ts_type": ts_type,
        "nullable": nullable,
        "primary_key": primary,
        "unique": flags.get("unique", False),
        "auto": identity is not None,
        "identity": identity,
    }


def capture_interfaces(parsed: ParsedFile, rel: str) -> dict[str, dict[str, tuple[str, bool]]]:
    """Return ``{Interface: {field: (ts type, nullable)}}`` from a models module."""
    interfaces: dict[str, dict[str, tuple[str, bool]]] = {}
    for statement in t.field_list(parsed.tree, "statements"):
        kind = t.kind(statement)
        if kind == "EmptyStatement":
            continue
        if kind not in {"InterfaceDeclaration", "TypeAliasDeclaration"}:
            raise ValueError(
                f"{rel}: only exported interfaces or object type aliases are qualified"
            )
        if t.modifier_kinds(statement) != {"ExportKeyword"}:
            raise ValueError(f"{rel}: row types must be exported")
        name = t.identifier_name(t.field(statement, "name"))
        if name is None or not STRUCT.fullmatch(name) or name in RESERVED_STRUCTS:
            raise ValueError(f"{rel}: row type names must be exported Rust struct identifiers")
        if t.field_list(statement, "typeParameters") or t.field_list(statement, "heritageClauses"):
            raise ValueError(f"{rel}: generic or extended row types require additional capture")
        body = statement if kind == "InterfaceDeclaration" else t.field(statement, "type")
        if body is None or (kind == "TypeAliasDeclaration" and t.kind(body) != "TypeLiteral"):
            raise ValueError(f"{rel}: {name} must be an object type")
        members: dict[str, tuple[str, bool]] = {}
        for member in t.field_list(body, "members"):
            field = t.identifier_name(t.field(member, "name"))
            value = t.field(member, "type")
            if (
                t.kind(member) != "PropertySignature"
                or field is None
                or value is None
                or t.field(member, "questionToken") is not None
                or t.modifier_kinds(member)
            ):
                raise ValueError(f"{rel}: {name} members must be required, plain properties")
            if field in members:
                raise ValueError(f"{rel}: {name} declares {field!r} twice")
            members[field] = _member_type(value, rel, name, field)
        if not members:
            raise ValueError(f"{rel}: {name} declares no members")
        if name in interfaces:
            raise ValueError(f"{rel}: duplicate row type {name}")
        interfaces[name] = members
    if not interfaces:
        raise ValueError(f"{rel}: no exported row types")
    return interfaces


def _member_type(node: t.Node, rel: str, name: str, field: str) -> tuple[str, bool]:
    kind = t.kind(node)
    if kind in TYPESCRIPT_TYPES:
        return TYPESCRIPT_TYPES[kind], False
    if kind == "UnionType":
        types = t.field_list(node, "types")
        scalars = [item for item in types if t.kind(item) in TYPESCRIPT_TYPES]
        nulls = [
            item
            for item in types
            if t.kind(item) == "LiteralType"
            and t.kind(t.field(item, "literal") or {}) == "NullKeyword"
        ]
        if len(types) == 2 and len(scalars) == 1 and len(nulls) == 1:
            return TYPESCRIPT_TYPES[t.kind(scalars[0])], True
    raise ValueError(f"{rel}: {name}.{field} must be number, string, boolean or one of them | null")


def match_models(
    tables: list[dict[str, Any]], interfaces: dict[str, dict[str, tuple[str, bool]]]
) -> list[dict[str, Any]]:
    """Bind each table to the single interface with identical columns, types and nullability."""
    models: list[dict[str, Any]] = []
    used: set[str] = set()
    for table in tables:
        expected = {
            field["name"]: (field["ts_type"], field["nullable"]) for field in table["fields"]
        }
        candidates = sorted(name for name, members in interfaces.items() if members == expected)
        if not candidates:
            raise ValueError(f"table {table['table']!r} has no row type with matching columns")
        if len(candidates) > 1:
            raise ValueError(f"table {table['table']!r} matches several row types: {candidates}")
        name = candidates[0]
        if name in used:
            raise ValueError(f"row type {name} matches several tables")
        used.add(name)
        models.append({"name": name, "table": table["table"], "fields": table["fields"]})
    unused = sorted(set(interfaces) - used)
    if unused:
        raise ValueError(f"row types without a table: {unused}")
    return models
