# SPDX-License-Identifier: Apache-2.0
"""Review-bound scan and plan; generation arrives with the native emitters."""

from __future__ import annotations

from pathlib import Path

from sanka_extensions.code import (
    ExtensionRequest,
    ExtensionResponse,
    failure_response,
    success_response,
)

from .capture import VERSION, canonical, capture, configuration, digest

EXTENSION_ID = "sanka/react-native-to-native"
PLAN_SCHEMA = "sanka.react-native-to-native.plan/v1"
LIMITATIONS = [
    "Scan and plan only: no SwiftUI or Compose code is generated by this version.",
    "Screen dispositions are static facts; structural parity is verified after generation.",
]


def _safe(root: Path, path: Path) -> Path:
    if not path.is_relative_to(root) or path == root:
        raise ValueError("artifacts must be inside the project")
    if any(item.is_symlink() for item in (path, *path.parents)):
        raise ValueError("artifact paths must not contain symlinks")
    return path


def handle(request: ExtensionRequest) -> ExtensionResponse:
    try:
        if request.extension_id != EXTENSION_ID or request.extension_version != VERSION:
            raise ValueError("extension identity or version mismatch")
        root = Path(request.project_root)
        if root != root.resolve() or not root.is_dir():
            raise ValueError("project_root must be a canonical directory")
        artifacts = _safe(root, Path(request.artifact_root))
        if not artifacts.is_relative_to(root / ".sanka"):
            raise ValueError("artifact_root must be under the project's .sanka directory")
        if request.command not in {"scan", "plan"}:
            return failure_response(
                request,
                code="SANKA_EXTENSION_UNSUPPORTED_COMMAND",
                message=(
                    f"Unsupported command: {request.command}; native generation, tests and "
                    "verification arrive with the SwiftUI and Compose emitters"
                ),
            )
        config = configuration(request.configuration)
        captured = capture(root, config)
        if request.command == "scan":
            data = captured
            name = "scan.json"
        else:
            data = {
                "schema": PLAN_SCHEMA,
                "extension_version": VERSION,
                "capture": captured,
                "files": {},
                "generated": False,
                "readiness": captured["readiness"],
                "dispositions": [
                    {
                        "module": screen["module"],
                        "disposition": screen["disposition"],
                        "adaptation_reasons": screen["adaptation_reasons"],
                    }
                    for screen in captured["screens"]
                ],
            }
            data["plan_hash"] = digest(data)
            name = "plan.json"
        artifacts.mkdir(parents=True, exist_ok=True)
        destination = _safe(root, artifacts / name)
        destination.write_text(canonical(data) + "\n")
        return success_response(
            request,
            data=data,
            artifacts=[str(destination)],
            limitations=LIMITATIONS,
        )
    except (ValueError, OSError) as error:
        return failure_response(
            request, code="SANKA_EXTENSION_EXECUTION_FAILED", message=str(error)
        )
