# SPDX-License-Identifier: Apache-2.0
"""Fixed Swift sources shipped with every generated SwiftUI package.

These files do not depend on the captured application: the normalized tree types and
their canonical JSON encoding, the bounded style modifier, the navigation environment
and the replay driver shared by the generated screens.
"""

from __future__ import annotations

from .tree import PROBE_TEXT

HEADER = (
    "// SPDX-License-Identifier: Apache-2.0\n"
    "// Generated by sanka/react-native-to-native from the capture in contract.json.\n"
)

STYLE_FIELDS: tuple[tuple[str, str], ...] = (
    ("flex", "Double"),
    ("flexDirection", "String"),
    ("justifyContent", "String"),
    ("alignItems", "String"),
    ("alignSelf", "String"),
    ("flexWrap", "String"),
    ("gap", "Double"),
    ("rowGap", "Double"),
    ("columnGap", "Double"),
    ("padding", "Double"),
    ("paddingHorizontal", "Double"),
    ("paddingVertical", "Double"),
    ("paddingTop", "Double"),
    ("paddingBottom", "Double"),
    ("paddingLeft", "Double"),
    ("paddingRight", "Double"),
    ("margin", "Double"),
    ("marginHorizontal", "Double"),
    ("marginVertical", "Double"),
    ("marginTop", "Double"),
    ("marginBottom", "Double"),
    ("marginLeft", "Double"),
    ("marginRight", "Double"),
    ("width", "Double"),
    ("height", "Double"),
    ("minWidth", "Double"),
    ("minHeight", "Double"),
    ("borderRadius", "Double"),
    ("borderWidth", "Double"),
    ("borderTopWidth", "Double"),
    ("borderBottomWidth", "Double"),
    ("borderLeftWidth", "Double"),
    ("borderRightWidth", "Double"),
    ("fontSize", "Double"),
    ("lineHeight", "Double"),
    ("opacity", "Double"),
    ("backgroundColor", "String"),
    ("color", "String"),
    ("borderColor", "String"),
    ("borderTopColor", "String"),
    ("borderBottomColor", "String"),
    ("tintColor", "String"),
    ("textAlign", "String"),
    ("fontWeight", "String"),
    ("fontStyle", "String"),
    ("textTransform", "String"),
    ("overflow", "String"),
)

TREE_SWIFT = (
    HEADER
    + """// The normalized screen tree compared by the structural parity replay. Layout, colors
// and pixels are not part of it; see the package README for the vocabulary.
import Foundation

public indirect enum JSONValue: Equatable {
    case null
    case bool(Bool)
    case number(Double)
    case string(String)
    case array([JSONValue])
    case object([String: JSONValue])

    public var stringValue: String? {
        if case .string(let value) = self { return value }
        return nil
    }

    public var numberValue: Double? {
        if case .number(let value) = self { return value }
        return nil
    }

    public var boolValue: Bool? {
        if case .bool(let value) = self { return value }
        return nil
    }

    public var arrayValue: [JSONValue]? {
        if case .array(let value) = self { return value }
        return nil
    }

    public var objectValue: [String: JSONValue]? {
        if case .object(let value) = self { return value }
        return nil
    }

    /// Canonical JSON: sorted keys, no whitespace, JavaScript number formatting.
    public var encoded: String {
        switch self {
        case .null:
            return "null"
        case .bool(let value):
            return value ? "true" : "false"
        case .number(let value):
            return jsString(value)
        case .string(let value):
            return jsonString(value)
        case .array(let items):
            return "[" + items.map { $0.encoded }.joined(separator: ",") + "]"
        case .object(let fields):
            let members = fields.keys.sorted().map { key in
                jsonString(key) + ":" + (fields[key] ?? .null).encoded
            }
            return "{" + members.joined(separator: ",") + "}"
        }
    }
}

func jsonString(_ value: String) -> String {
    var result = "\\""
    for scalar in value.unicodeScalars {
        switch scalar {
        case "\\"": result += "\\\\\\""
        case "\\\\": result += "\\\\\\\\"
        case "\\n": result += "\\\\n"
        case "\\r": result += "\\\\r"
        case "\\t": result += "\\\\t"
        default:
            if scalar.value < 0x20 {
                result += String(format: "\\\\u%04x", scalar.value)
            } else {
                result.unicodeScalars.append(scalar)
            }
        }
    }
    return result + "\\""
}

/// JavaScript `String(number)` for the values a screen can produce: integers print
/// without a fraction, other finite numbers use Swift's shortest representation.
public func jsString(_ value: Double) -> String {
    if value.isNaN { return "NaN" }
    if value.isInfinite { return value < 0 ? "-Infinity" : "Infinity" }
    if value == value.rounded() && abs(value) < 9_007_199_254_740_992 {
        return String(Int64(value))
    }
    return "\\(value)"
}

public func jsString(_ value: Bool) -> String {
    value ? "true" : "false"
}

public func jsString(_ value: String) -> String {
    value
}

public enum Intent: Equatable {
    case navigate(String, [String: JSONValue])
    case push(String, [String: JSONValue])
    case back
    case set(String, JSONValue)
    case bind(String)
    case run(String)
    case store(String, String)

    public var json: JSONValue {
        switch self {
        case .navigate(let name, let params):
            return .object(["navigate": .string(name), "params": .object(params)])
        case .push(let path, let params):
            return .object(["push": .string(path), "params": .object(params)])
        case .back:
            return .object(["back": .bool(true)])
        case .set(let name, let value):
            return .object(["set": .string(name), "value": value])
        case .bind(let name):
            return .object(["bind": .string(name)])
        case .run(let effect):
            return .object(["run": .string(effect)])
        case .store(let key, let value):
            return .object(["store": .string(key), "value": .string(value)])
        }
    }
}

public struct Node: Equatable {
    public var role: String
    public var text: String?
    public var label: String?
    public var enabled: Bool?
    public var checked: Bool?
    public var action: [Intent]?
    public var children: [Node]

    public init(
        role: String,
        text: String? = nil,
        label: String? = nil,
        enabled: Bool? = nil,
        checked: Bool? = nil,
        action: [Intent]? = nil,
        children: [Node] = []
    ) {
        self.role = role
        self.text = text
        self.label = label
        self.enabled = enabled
        self.checked = checked
        self.action = action
        self.children = children
    }

    public var json: JSONValue {
        .object([
            "role": .string(role),
            "text": text.map(JSONValue.string) ?? .null,
            "label": label.map(JSONValue.string) ?? .null,
            "enabled": enabled.map(JSONValue.bool) ?? .null,
            "checked": checked.map(JSONValue.bool) ?? .null,
            "action": action.map { .array($0.map { $0.json }) } ?? .null,
            "children": .array(children.map { $0.json }),
        ])
    }

    /// Interactive nodes in document order with their child-index paths.
    public func interactive() -> [(path: String, node: Node)] {
        var found: [(path: String, node: Node)] = []
        collect(into: &found, path: [])
        return found
    }

    private func collect(into found: inout [(path: String, node: Node)], path: [Int]) {
        if role == "button" || role == "switch" || role == "textfield" {
            found.append((path: path.map(String.init).joined(separator: "."), node: self))
        }
        for (index, child) in children.enumerated() {
            child.collect(into: &found, path: path + [index])
        }
    }
}

public struct SankaKeyed<Element>: Identifiable {
    public let id: String
    public let element: Element
}

public func sankaKeyed<Element>(
    _ elements: [Element], key: (Element) -> String
) -> [SankaKeyed<Element>] {
    elements.map { SankaKeyed(id: key($0), element: $0) }
}

public func decodeArray<Element>(
    _ json: JSONValue?, _ decode: (JSONValue) -> Element?
) -> [Element]? {
    guard let items = json?.arrayValue else { return nil }
    var result: [Element] = []
    for item in items {
        guard let value = decode(item) else { return nil }
        result.append(value)
    }
    return result
}

/// Decodes `null` to `.some(nil)`; a value that fails to decode yields `nil`.
public func decodeOptional<Element>(
    _ json: JSONValue?, _ decode: (JSONValue) -> Element?
) -> Element?? {
    guard let json = json else { return nil }
    if json == .null { return .some(nil) }
    guard let value = decode(json) else { return nil }
    return .some(.some(value))
}

public let sankaProbeText = @PROBE@

/// A generated screen: state, reducer, effects and the normalized tree of any state.
public protocol SankaScreen {
    associatedtype ScreenState
    associatedtype ScreenParams
    static var screenName: String { get }
    static var module: String { get }
    static var initialState: ScreenState { get }
    static var sampleParams: ScreenParams { get }
    static var sampleParamsJSON: JSONValue { get }
    /// Effect ids run when the screen appears, in declaration order.
    static var appearEffects: [String] { get }
    /// Effect ids that submit a form (POST requests).
    static var submitEffects: [String] { get }
    static func tree(state: ScreenState, params: ScreenParams) -> Node
    static func apply(intent: Intent, to state: inout ScreenState) -> Bool
    /// Runs one effect against the state and returns every intent it raised, in order.
    @MainActor
    static func run(
        effect: String,
        state: inout ScreenState,
        params: ScreenParams,
        transport: SankaTransport,
        storage: SankaStorage
    ) async -> [Intent]
}

extension SankaScreen {
    /// The replay scenarios: the initial tree with requests in flight, the trees after the
    /// appear effects succeed and fail, and the tree after activating each state-changing
    /// button, switch and text field and each submitting button (success and failure).
    @MainActor
    public static func replay(fixtures: SankaFixtures) async -> [JSONValue] {
        let entries = fixtures.effects[module] ?? [:]
        var documents: [JSONValue] = []
        var initial = initialState
        let pendingTransport = SankaFixtureTransport(fixtures: entries, defaultMode: .pending)
        let pendingStorage = SankaMemoryStorage(values: fixtures.storage, pending: true)
        let initialRaised = await appear(
            &initial, transport: pendingTransport, storage: pendingStorage
        )
        documents.append(
            document("initial", initial, raised: initialRaised, requests: pendingTransport.requests)
        )
        var base = initial
        if !appearEffects.isEmpty {
            var loaded = initialState
            let okTransport = SankaFixtureTransport(fixtures: entries, defaultMode: .success)
            let okStorage = SankaMemoryStorage(values: fixtures.storage, pending: false)
            let loadedRaised = await appear(&loaded, transport: okTransport, storage: okStorage)
            documents.append(
                document("loaded", loaded, raised: loadedRaised, requests: okTransport.requests)
            )
            var failed = initialState
            let failTransport = SankaFixtureTransport(fixtures: entries, defaultMode: .failure)
            let failStorage = SankaMemoryStorage(values: fixtures.storage, pending: false)
            let failedRaised = await appear(&failed, transport: failTransport, storage: failStorage)
            let failedDocument = document(
                "load-failed", failed, raised: failedRaised, requests: failTransport.requests
            )
            documents.append(failedDocument)
            base = loaded
        }
        for (path, node) in tree(state: base, params: sampleParams).interactive() {
            guard let intents = node.action else { continue }
            let submits = intents.compactMap { intent -> String? in
                if case .run(let effect) = intent, submitEffects.contains(effect) { return effect }
                return nil
            }
            if !submits.isEmpty {
                for mode in [SankaFixtureMode.success, .failure] {
                    var state = base
                    let transport = SankaFixtureTransport(fixtures: entries, defaultMode: .success)
                    for effect in submits { transport.modes[effect] = mode }
                    let storage = SankaMemoryStorage(values: fixtures.storage, pending: false)
                    let outcome = await activate(
                        node, intents, &state, transport: transport, storage: storage
                    )
                    let name = (mode == .success ? "submit:" : "submit-failed:") + path
                    documents.append(
                        document(name, state, raised: outcome.raised, requests: transport.requests)
                    )
                }
                continue
            }
            var state = base
            let transport = SankaFixtureTransport(fixtures: entries, defaultMode: .success)
            let storage = SankaMemoryStorage(values: fixtures.storage, pending: false)
            let outcome = await activate(
                node, intents, &state, transport: transport, storage: storage
            )
            guard outcome.applied else { continue }
            let name = scenarioKind(node.role) + ":" + path
            documents.append(
                document(name, state, raised: outcome.raised, requests: transport.requests)
            )
        }
        return documents
    }

    @MainActor
    private static func appear(
        _ state: inout ScreenState, transport: SankaTransport, storage: SankaStorage
    ) async -> [Intent] {
        var raised: [Intent] = []
        for effect in appearEffects {
            raised += await run(
                effect: effect, state: &state, params: sampleParams, transport: transport,
                storage: storage
            )
        }
        return raised
    }

    /// Performs a node's intents the way the view would: state changes through the
    /// reducer, effects through `run`, everything else recorded only.
    @MainActor
    private static func activate(
        _ node: Node,
        _ intents: [Intent],
        _ state: inout ScreenState,
        transport: SankaTransport,
        storage: SankaStorage
    ) async -> (raised: [Intent], applied: Bool) {
        var raised: [Intent] = []
        var applied = false
        for intent in intents {
            switch intent {
            case .bind(let name):
                let value: JSONValue
                if node.role == "switch" {
                    value = .bool(!(node.checked ?? false))
                } else if node.role == "textfield" {
                    value = .string(sankaProbeText)
                } else {
                    continue
                }
                let concrete = Intent.set(name, value)
                if apply(intent: concrete, to: &state) {
                    applied = true
                    raised.append(concrete)
                }
            case .set:
                if apply(intent: intent, to: &state) {
                    applied = true
                    raised.append(intent)
                }
            case .run(let effect):
                raised += await run(
                    effect: effect, state: &state, params: sampleParams, transport: transport,
                    storage: storage
                )
            case .store(let key, let value):
                await storage.set(key, value)
                raised.append(intent)
            default:
                raised.append(intent)
            }
        }
        return (raised, applied)
    }

    private static func scenarioKind(_ role: String) -> String {
        if role == "switch" { return "toggle" }
        return role == "textfield" ? "type" : "press"
    }

    private static func document(
        _ scenario: String, _ state: ScreenState, raised: [Intent], requests: [SankaRequest]
    ) -> JSONValue {
        .object([
            "screen": .string(screenName),
            "scenario": .string(scenario),
            "params": sampleParamsJSON,
            "tree": tree(state: state, params: sampleParams).json,
            "raised": .array(raised.map { $0.json }),
            "requests": .array(requests.map { $0.json }),
        ])
    }
}
"""
).replace("@PROBE@", '"' + PROBE_TEXT + '"')


def styles_runtime() -> str:
    """The style value type, its merge rule and the SwiftUI modifier applying it."""
    declarations = "\n".join(f"    public var {name}: {kind}?" for name, kind in STYLE_FIELDS)
    parameters = ",\n".join(f"        {name}: {kind}? = nil" for name, kind in STYLE_FIELDS)
    assignments = "\n".join(f"        self.{name} = {name}" for name, _ in STYLE_FIELDS)
    merges = "\n".join(
        f"        if let value = other.{name} {{ result.{name} = value }}"
        for name, _ in STYLE_FIELDS
    )
    return (
        HEADER
        + """// StyleSheet entries as one bounded value type; layout is approximated, not compared.
import SwiftUI

public struct SankaStyle: Equatable {
@DECLARATIONS@

    public init(
@PARAMETERS@
    ) {
@ASSIGNMENTS@
    }

    /// Later entries of a React Native style array win.
    public func merging(_ other: SankaStyle) -> SankaStyle {
        var result = self
@MERGES@
        return result
    }
}

public func sankaColor(_ value: String?) -> Color {
    guard let value = value else { return .clear }
    switch value {
    case "black": return .black
    case "white": return .white
    case "transparent": return .clear
    case "red": return .red
    case "green": return .green
    case "blue": return .blue
    case "gray", "grey": return .gray
    default: break
    }
    if value.hasPrefix("#") {
        var digits = String(value.dropFirst())
        if digits.count == 3 || digits.count == 4 {
            digits = digits.map { "\\($0)\\($0)" }.joined()
        }
        guard digits.count == 6 || digits.count == 8, let number = UInt64(digits, radix: 16) else {
            return .clear
        }
        let alpha = digits.count == 8 ? Double(number & 0xff) / 255 : 1
        let rgb = digits.count == 8 ? number >> 8 : number
        return Color(
            red: Double((rgb >> 16) & 0xff) / 255,
            green: Double((rgb >> 8) & 0xff) / 255,
            blue: Double(rgb & 0xff) / 255,
            opacity: alpha
        )
    }
    if value.hasPrefix("rgb") {
        let inside = value.drop { $0 != "(" }.dropFirst().prefix { $0 != ")" }
        let parts = inside.split(separator: ",").map {
            Double($0.trimmingCharacters(in: .whitespaces)) ?? 0
        }
        guard parts.count == 3 || parts.count == 4 else { return .clear }
        return Color(
            red: parts[0] / 255,
            green: parts[1] / 255,
            blue: parts[2] / 255,
            opacity: parts.count == 4 ? parts[3] : 1
        )
    }
    return .clear
}

func sankaWeight(_ value: String?) -> Font.Weight {
    switch value ?? "normal" {
    case "100": return .ultraLight
    case "200": return .thin
    case "300": return .light
    case "500": return .medium
    case "600": return .semibold
    case "700", "bold": return .bold
    case "800": return .heavy
    case "900": return .black
    default: return .regular
    }
}

func sankaTextAlignment(_ value: String?) -> TextAlignment {
    switch value ?? "auto" {
    case "center": return .center
    case "right": return .trailing
    default: return .leading
    }
}

func sankaTextCase(_ value: String?) -> Text.Case? {
    switch value ?? "none" {
    case "uppercase": return .uppercase
    case "lowercase": return .lowercase
    default: return nil
    }
}

func sankaLength(_ value: Double?) -> CGFloat? {
    value.map { CGFloat($0) }
}

func sankaFont(_ style: SankaStyle) -> Font? {
    if style.fontSize == nil && style.fontWeight == nil { return nil }
    return .system(size: CGFloat(style.fontSize ?? 17), weight: sankaWeight(style.fontWeight))
}

func sankaInsets(_ style: SankaStyle, margin: Bool) -> EdgeInsets {
    if margin {
        return EdgeInsets(
            top: sankaLength(style.marginTop ?? style.marginVertical ?? style.margin) ?? 0,
            leading: sankaLength(style.marginLeft ?? style.marginHorizontal ?? style.margin) ?? 0,
            bottom: sankaLength(style.marginBottom ?? style.marginVertical ?? style.margin) ?? 0,
            trailing: sankaLength(style.marginRight ?? style.marginHorizontal ?? style.margin) ?? 0
        )
    }
    return EdgeInsets(
        top: sankaLength(style.paddingTop ?? style.paddingVertical ?? style.padding) ?? 0,
        leading: sankaLength(style.paddingLeft ?? style.paddingHorizontal ?? style.padding) ?? 0,
        bottom: sankaLength(style.paddingBottom ?? style.paddingVertical ?? style.padding) ?? 0,
        trailing: sankaLength(style.paddingRight ?? style.paddingHorizontal ?? style.padding) ?? 0
    )
}

struct SankaStyleModifier: ViewModifier {
    let style: SankaStyle

    func body(content: Content) -> some View {
        let expands = (style.flex ?? 0) > 0
        let radius = sankaLength(style.borderRadius) ?? 0
        let borderColor = style.borderColor ?? style.borderBottomColor ?? style.borderTopColor
        let borderWidth = style.borderWidth ?? style.borderBottomWidth ?? style.borderTopWidth
        content
            .font(sankaFont(style))
            .italic(style.fontStyle == "italic")
            .foregroundStyle(style.color.map(sankaColor) ?? Color.primary)
            .multilineTextAlignment(sankaTextAlignment(style.textAlign))
            .textCase(sankaTextCase(style.textTransform))
            .lineSpacing(max(0, (style.lineHeight ?? 0) - (style.fontSize ?? 17)))
            .padding(sankaInsets(style, margin: false))
            .frame(width: sankaLength(style.width), height: sankaLength(style.height))
            .frame(minWidth: sankaLength(style.minWidth), minHeight: sankaLength(style.minHeight))
            .frame(
                maxWidth: expands ? .infinity : nil,
                maxHeight: expands ? .infinity : nil,
                alignment: .topLeading
            )
            .background(sankaColor(style.backgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: radius))
            .overlay(
                RoundedRectangle(cornerRadius: radius)
                    .strokeBorder(sankaColor(borderColor), lineWidth: sankaLength(borderWidth) ?? 0)
            )
            .opacity(style.opacity ?? 1)
            .padding(sankaInsets(style, margin: true))
    }
}

extension View {
    public func sankaStyle(_ style: SankaStyle) -> some View {
        modifier(SankaStyleModifier(style: style))
    }
}

@ViewBuilder
public func sankaImage(uri: String, contentMode: ContentMode) -> some View {
    AsyncImage(url: URL(string: uri)) { image in
        image.resizable().aspectRatio(contentMode: contentMode)
    } placeholder: {
        Color.clear
    }
}
""".replace("@DECLARATIONS@", declarations)
        .replace("@PARAMETERS@", parameters)
        .replace("@ASSIGNMENTS@", assignments)
        .replace("@MERGES@", merges)
    )


ASSET_IMAGE_SWIFT = """
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

/// Loads a copied asset from the package resource bundle by its project-relative path.
public func sankaImage(asset path: String, contentMode: ContentMode) -> some View {
    var segments = path.split(separator: "/").map(String.init)
    let file = segments.removeLast()
    let pieces = file.split(separator: ".", omittingEmptySubsequences: false).map(String.init)
    let ext = pieces.count > 1 ? pieces.last ?? "" : ""
    let name = pieces.count > 1 ? pieces.dropLast().joined(separator: ".") : file
    let url = Bundle.module.url(
        forResource: name,
        withExtension: ext.isEmpty ? nil : ext,
        subdirectory: segments.isEmpty ? nil : segments.joined(separator: "/")
    )
    #if canImport(UIKit)
    if let url = url, let image = UIImage(contentsOfFile: url.path) {
        return Image(uiImage: image).resizable().aspectRatio(contentMode: contentMode)
    }
    #elseif canImport(AppKit)
    if let url = url, let image = NSImage(contentsOf: url) {
        return Image(nsImage: image).resizable().aspectRatio(contentMode: contentMode)
    }
    #endif
    return Image(systemName: "photo").resizable().aspectRatio(contentMode: contentMode)
}
"""

NAVIGATION_RUNTIME = """
/// Typed navigation intents a screen raises; the root view turns them into path changes.
public struct SankaNavigator {
    public var navigate: (Route) -> Void
    public var back: () -> Void

    public init(navigate: @escaping (Route) -> Void, back: @escaping () -> Void) {
        self.navigate = navigate
        self.back = back
    }
}

private struct SankaNavigatorKey: EnvironmentKey {
    static let defaultValue = SankaNavigator(navigate: { _ in }, back: {})
}

extension EnvironmentValues {
    public var sankaNavigator: SankaNavigator {
        get { self[SankaNavigatorKey.self] }
        set { self[SankaNavigatorKey.self] = newValue }
    }
}

extension View {
    @ViewBuilder
    func sankaHeader(title: String?, visible: Bool) -> some View {
        #if os(iOS)
        if visible {
            self.navigationTitle(title ?? "")
        } else {
            self.toolbar(.hidden, for: .navigationBar)
        }
        #else
        self.navigationTitle(title ?? "")
        #endif
    }
}
"""


API_CLIENT_SWIFT = (
    HEADER
    + """// Network and storage behind injectable protocols: URLSession and UserDefaults in the
// app, fixtures in the tree dump and previews. JSON is parsed once into JSONValue and
// decoded by the generated value types, so the app and the replay share one code path.
import Foundation
import SwiftUI

public struct SankaRequest: Equatable {
    public var effect: String
    public var method: String
    public var url: String
    public var headers: [String: String]
    public var body: JSONValue?

    public init(
        effect: String, method: String, url: String, headers: [String: String], body: JSONValue?
    ) {
        self.effect = effect
        self.method = method
        self.url = url
        self.headers = headers
        self.body = body
    }

    public var json: JSONValue {
        .object([
            "effect": .string(effect),
            "method": .string(method),
            "url": .string(url),
            "headers": .object(headers.mapValues { JSONValue.string($0) }),
            "body": body ?? .null,
        ])
    }
}

public struct SankaResponse {
    public var status: Int
    public var body: Data

    public init(status: Int, body: Data) {
        self.status = status
        self.body = body
    }

    public func json() throws -> JSONValue {
        try JSONValue.parse(body)
    }
}

public enum SankaAPIError: Error {
    case transport(String)
    case status(Int)
    case decoding
    case fixture(String)
    /// The request is still in flight (only the replay's `initial` scenario raises it).
    case pending
}

public protocol SankaTransport {
    func send(_ request: SankaRequest) async throws -> SankaResponse
}

public protocol SankaStorage {
    func get(_ key: String) async throws -> String?
    func set(_ key: String, _ value: String) async
}

public func decodeResponse<Value>(
    _ response: SankaResponse, _ decode: (JSONValue) -> Value?
) throws -> Value {
    guard let value = decode(try response.json()) else { throw SankaAPIError.decoding }
    return value
}

public struct URLSessionTransport: SankaTransport {
    public init() {}

    public func send(_ request: SankaRequest) async throws -> SankaResponse {
        guard let url = URL(string: request.url) else {
            throw SankaAPIError.transport("invalid url " + request.url)
        }
        var urlRequest = URLRequest(url: url)
        urlRequest.httpMethod = request.method
        for (name, value) in request.headers {
            urlRequest.setValue(value, forHTTPHeaderField: name)
        }
        if let body = request.body {
            urlRequest.httpBody = Data(body.encoded.utf8)
        }
        let (data, response) = try await URLSession.shared.data(for: urlRequest)
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        return SankaResponse(status: status, body: data)
    }
}

public struct UserDefaultsStorage: SankaStorage {
    public init() {}

    public func get(_ key: String) async throws -> String? {
        UserDefaults.standard.string(forKey: key)
    }

    public func set(_ key: String, _ value: String) async {
        UserDefaults.standard.set(value, forKey: key)
    }
}

public enum SankaFixtureMode {
    case pending
    case success
    case failure
}

/// Fixture responses keyed by effect id, as `verify-cases.json` declares them.
public final class SankaFixtureTransport: SankaTransport {
    public let fixtures: [String: JSONValue]
    public var defaultMode: SankaFixtureMode
    public var modes: [String: SankaFixtureMode] = [:]
    public private(set) var requests: [SankaRequest] = []

    public init(fixtures: [String: JSONValue], defaultMode: SankaFixtureMode) {
        self.fixtures = fixtures
        self.defaultMode = defaultMode
    }

    public func send(_ request: SankaRequest) async throws -> SankaResponse {
        requests.append(request)
        let mode = modes[request.effect] ?? defaultMode
        if mode == .pending { throw SankaAPIError.pending }
        guard let entry = fixtures[request.effect]?.objectValue else {
            throw SankaAPIError.fixture("no fixture for effect " + request.effect)
        }
        let key = mode == .success ? "response" : "failure"
        guard let fixture = entry[key]?.objectValue else {
            throw SankaAPIError.fixture("no " + key + " fixture for effect " + request.effect)
        }
        if fixture["error"] != nil { throw SankaAPIError.transport("fixture network failure") }
        guard let status = fixture["status"]?.numberValue, let body = fixture["body"] else {
            throw SankaAPIError.fixture("fixture for " + request.effect + " needs status and body")
        }
        return SankaResponse(status: Int(status), body: Data(body.encoded.utf8))
    }
}

public final class SankaMemoryStorage: SankaStorage {
    public var values: [String: String]
    public var pending: Bool

    public init(values: [String: String], pending: Bool) {
        self.values = values
        self.pending = pending
    }

    public func get(_ key: String) async throws -> String? {
        if pending { throw SankaAPIError.pending }
        return values[key]
    }

    public func set(_ key: String, _ value: String) async {
        values[key] = value
    }
}

public struct SankaFixtures {
    public var storage: [String: String]
    public var effects: [String: [String: JSONValue]]

    public static let empty = SankaFixtures(storage: [:], effects: [:])

    public init(storage: [String: String], effects: [String: [String: JSONValue]]) {
        self.storage = storage
        self.effects = effects
    }

    /// Reads `verify-cases.json`: `storage` and `screens.<module>.effects.<id>`.
    public static func load(path: String) throws -> SankaFixtures {
        let document = try JSONValue.parse(Data(contentsOf: URL(fileURLWithPath: path)))
        guard let root = document.objectValue else { throw SankaAPIError.fixture("not an object") }
        var storage: [String: String] = [:]
        for (key, value) in root["storage"]?.objectValue ?? [:] {
            guard let text = value.stringValue else {
                throw SankaAPIError.fixture("storage values must be strings")
            }
            storage[key] = text
        }
        var effects: [String: [String: JSONValue]] = [:]
        for (module, screen) in root["screens"]?.objectValue ?? [:] {
            effects[module] = screen.objectValue?["effects"]?.objectValue ?? [:]
        }
        return SankaFixtures(storage: storage, effects: effects)
    }
}

extension JSONValue {
    public static func parse(_ data: Data) throws -> JSONValue {
        let object = try JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed])
        return try JSONValue(any: object)
    }

    public init(any value: Any) throws {
        if value is NSNull {
            self = .null
        } else if let number = value as? NSNumber {
            if CFGetTypeID(number) == CFBooleanGetTypeID() {
                self = .bool(number.boolValue)
            } else {
                self = .number(number.doubleValue)
            }
        } else if let text = value as? String {
            self = .string(text)
        } else if let items = value as? [Any] {
            self = .array(try items.map { try JSONValue(any: $0) })
        } else if let fields = value as? [String: Any] {
            self = .object(try fields.mapValues { try JSONValue(any: $0) })
        } else {
            throw SankaAPIError.decoding
        }
    }
}

private struct SankaTransportKey: EnvironmentKey {
    static let defaultValue: SankaTransport = URLSessionTransport()
}

private struct SankaStorageKey: EnvironmentKey {
    static let defaultValue: SankaStorage = UserDefaultsStorage()
}

extension EnvironmentValues {
    public var sankaTransport: SankaTransport {
        get { self[SankaTransportKey.self] }
        set { self[SankaTransportKey.self] = newValue }
    }

    public var sankaStorage: SankaStorage {
        get { self[SankaStorageKey.self] }
        set { self[SankaStorageKey.self] = newValue }
    }
}
"""
)
