# SPDX-License-Identifier: Apache-2.0
"""CI PostgreSQL qualification in a newly allocated, isolated schema."""

import hashlib
import json
import os
import subprocess
import sys
import uuid

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from test_database_migrations import schema

from sanka_extension_drf_to_flask.database import render_database


@pytest.mark.skipif(
    not os.environ.get("SANKA_MIGRATE_TEST_POSTGRES_DSN"),
    reason="requires the dedicated PostgreSQL test service",
)
def test_postgres_initial_schema_and_adoption_are_compatible(tmp_path):
    payload = schema()
    payload.pop("schema_hash")
    payload["dialect"] = "postgresql"
    parent = payload["tables"][0]
    parent["name"] = "z_parent"
    child_pk = dict(parent["columns"][0])
    child_fk = {
        **child_pk,
        "name": "parent_id",
        "attribute": "parent_id",
        "primary_key": False,
        "unique": False,
        "autoincrement": False,
        "references": {"table": "z_parent", "column": "id", "on_delete": "DO_NOTHING"},
    }
    payload["tables"].append(
        {
            "name": "a_child",
            "model": "fixture.Child",
            "columns": [child_pk, child_fk],
            "indexes": [],
            "unique_constraints": [],
        }
    )
    payload["schema_hash"] = (
        "sha256:"
        + hashlib.sha256(
            json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()
    )
    for name, content in render_database(payload).items():
        path = tmp_path / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    url = make_url(os.environ["SANKA_MIGRATE_TEST_POSTGRES_DSN"]).set(
        drivername="postgresql+psycopg"
    )
    isolated_schema = "sanka_flask_" + uuid.uuid4().hex
    admin = create_engine(url)
    with admin.begin() as connection:
        connection.execute(text('CREATE SCHEMA "' + isolated_schema + '"'))
    try:
        scoped = url.update_query_dict({"options": "-csearch_path=" + isolated_schema})
        script = """
from alembic import command
from alembic.config import Config
from sqlalchemy import text
from database import make_engine, check_schema, adopt_existing, EXPECTED_SCHEMA_HASH
engine = make_engine()
assert check_schema(engine)
command.upgrade(Config('alembic.ini'), 'head')
assert check_schema(engine) == [], check_schema(engine)
with engine.begin() as conn:
    key = conn.scalar(text("INSERT INTO z_parent(name) VALUES('kept') RETURNING id"))
    conn.execute(text('INSERT INTO a_child(parent_id) VALUES(:key)'), {'key': key})
adopt_existing(engine, EXPECTED_SCHEMA_HASH)
command.upgrade(Config('alembic.ini'), 'head')
with engine.connect() as conn:
    assert conn.scalar(text('SELECT count(*) FROM a_child')) == 1
with engine.begin() as conn:
    conn.execute(text('DROP INDEX item_name_desc'))
    conn.execute(text('CREATE INDEX item_name_desc ON z_parent(name ASC)'))
assert check_schema(engine) == ['z_parent: indexes differ']
with engine.begin() as conn:
    conn.execute(text('DROP INDEX item_name_desc'))
    conn.execute(text('CREATE INDEX item_name_desc ON z_parent(name DESC)'))
    conn.execute(text('ALTER TABLE a_child ALTER COLUMN parent_id '
                      'ADD GENERATED BY DEFAULT AS IDENTITY'))
assert check_schema(engine) == ['a_child.parent_id: unexpected identity']
engine.dispose()
"""
        result = subprocess.run(
            [sys.executable, "-c", script],
            cwd=tmp_path,
            env=os.environ | {"SANKA_DATABASE_URL": scoped.render_as_string(hide_password=False)},
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert result.returncode == 0, result.stderr
    finally:
        with admin.begin() as connection:
            connection.execute(text('DROP SCHEMA "' + isolated_schema + '" CASCADE'))
        admin.dispose()


@pytest.mark.skipif(
    not os.environ.get("SANKA_MIGRATE_TEST_POSTGRES_DSN"),
    reason="requires the dedicated PostgreSQL test service",
)
def test_postgres_adopts_schema_created_by_django(tmp_path):
    url = make_url(os.environ["SANKA_MIGRATE_TEST_POSTGRES_DSN"]).set(
        drivername="postgresql+psycopg"
    )
    isolated_schema = "sanka_django_" + uuid.uuid4().hex
    admin = create_engine(url)
    with admin.begin() as connection:
        connection.execute(text('CREATE SCHEMA "' + isolated_schema + '"'))
    try:
        django_database = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": url.database,
            "USER": url.username or "",
            "PASSWORD": url.password or "",
            "HOST": url.host or "",
            "PORT": str(url.port or ""),
            "OPTIONS": {"options": "-csearch_path=" + isolated_schema},
        }
        source_script = r"""import datetime
import json
import os
import uuid
from django.conf import settings
settings.configure(
    INSTALLED_APPS=[],
    DATABASES={"default": json.loads(os.environ["DJANGO_DATABASE"])},
    DEFAULT_AUTO_FIELD="django.db.models.AutoField",
    TIME_ZONE="UTC",
    USE_TZ=True,
)
import django
django.setup()
from django.db import connection, models
from sanka_code_migration.drf.models import capture_schema
class ExistingItem(models.Model):
    code = models.CharField(max_length=40, unique=True)
    notes = models.TextField(db_index=True)
    token = models.UUIDField(default=uuid.uuid4)
    posted = models.DateTimeField()
    class Meta:
        app_label = "fixture"
        db_table = "existing_item"
with connection.schema_editor() as editor:
    editor.create_model(ExistingItem)
ExistingItem.objects.create(
    code="kept",
    notes="source row",
    posted=datetime.datetime(2026, 1, 2, tzinfo=datetime.timezone.utc),
)
print(json.dumps(capture_schema([ExistingItem])))
"""
        source = subprocess.run(
            [sys.executable, "-c", source_script],
            cwd=tmp_path,
            env=os.environ | {"DJANGO_DATABASE": json.dumps(django_database)},
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert source.returncode == 0, source.stderr
        payload = json.loads(source.stdout)
        assert payload["gaps"] == []
        assert next(column for column in payload["tables"][0]["columns"] if column["name"] == "id")[
            "identity"
        ] == {"always": False}
        assert {
            tuple(index.get("opclasses", []))
            for index in payload["tables"][0]["indexes"]
            if index["name"].endswith("_like")
        } == {("varchar_pattern_ops",), ("text_pattern_ops",)}
        for name, content in render_database(payload).items():
            path = tmp_path / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        scoped = url.update_query_dict({"options": "-csearch_path=" + isolated_schema})
        adoption_script = r"""from sqlalchemy import text
from database import EXPECTED_SCHEMA_HASH, adopt_existing, check_schema, make_engine
engine = make_engine()
assert check_schema(engine) == [], check_schema(engine)
adopt_existing(engine, EXPECTED_SCHEMA_HASH)
assert check_schema(engine) == [], check_schema(engine)
with engine.connect() as connection:
    assert connection.scalar(text("SELECT count(*) FROM existing_item")) == 1
    assert connection.scalar(text("SELECT count(*) FROM alembic_version")) == 1
engine.dispose()
"""
        adoption = subprocess.run(
            [sys.executable, "-c", adoption_script],
            cwd=tmp_path,
            env=os.environ | {"SANKA_DATABASE_URL": scoped.render_as_string(hide_password=False)},
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert adoption.returncode == 0, adoption.stderr
    finally:
        with admin.begin() as connection:
            connection.execute(text('DROP SCHEMA "' + isolated_schema + '" CASCADE'))
        admin.dispose()
